### ISSUE TITLE
Lili's Foreword

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#12]
# Source Materials:  
[LiliForeword.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/LiliForward/LiliForeword.xml)   
[Foreword Transcription](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/LiliForward/Foreword_transcription.docx)    
[Foreword Images](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/LiliForward/Foreword_images.pdf)
[MIWschema.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/WIKIandREADMEmaterials/MIWschema.rng)

**Comment by Tatjanawj** [comment]
There is only one error that is highlighted in the XML file. The key used for "Grete" is spelled incorrectly. Instead of "wegnerG" it should be "wegenerG".

**Comment by bossa12** [comment]
'<persName key="sparreAn">Andreas Sparre</persName>' 7
'<persName key="wegenerE">Einar Wegener</persName>' 2
' <persName key="lili">Lili Elbe</persName>' 2
' <persName key="kreutz">Professor Kreutz</persName>'6

**Comment by bossa12** [comment]
1. respStmt
            
the "respStmt" element includes the person who is responsible for what section. In this case, Sabine Meyer is responsible for the German translation part. And the attribute value shows her reference is sm, which will help to locate her full name.

2. titleStmt
"titleStmt" element nests elements including "title", "author", "respStmt".  It helps to organize the contents of this article and the people who are involved working with it.

**Comment by RJP43** [comment]
Hi @bossa12  and @Tatjanawj!  👋   

Well done completing the TEI XML Exercise! :tada:   
The minor issue with your submission was each member of the team needed to "select two different elements used in the XML (in the .xml file) in order to reflect in 2-4 sentences how the project has further constrained the original TEI element" and unfortunately only one of you completed that task.      
  
For the next assignment, your team will need to reference the latest file added to the [Foreword's Folder 📂](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/LiliForward) -- a screenshot of the TEI header information provided by the project manager, Emily Datskou. As a team, you will work together to create a `<teiHeader>` element for Lili's Foreword using the information provided by Emily, the existing XML encoding, photograph(s) of the letter _(a.k.a the facsimile images)_, and the translation/transcription documents.    
 _(⬆️ all available in your text's folder linked above ⬆️)_
  
Be sure to reference the [TEI Header Exercise](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/Exercises/TEIheader_exercise.md) in order to let each other, @ProfPLC, and I know what tasks you each are comfortable with completing by Tuesday (2/26) 📆. Please remember the main goals in all of our assignments are team communication 💬  and collaboration 👐.   
  
 _Note: the TEI header template is available in [Thursday's lesson on Capturing Metadata](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Capturing-Metadata) and as a [download-able XML file containing the template `<teiHeader>`](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/TEIHeader_Template.xml)._ Happy coding! 💻 😃

**Comment by Tatjanawj** [comment]
Ran and I discussed in person how to divide up the task. She will be updating the metadata in the XML file from line 1 - 53 and I will be doing lines 54 - 97.

**Comment by bossa12** [comment]
<title>
               Letter to <persName key=""></persName>
            </title> 

We didn't get to use this element since it is for a letter and our task is an article. This element specifies the person is addressed to the letter and contains the attribute of this person's key id.

**Comment by RJP43** [comment]
@bossa12 yes, you are correct that in the template your team will not use the title element for letters instead your team should use the title element for texts with translations... 
````
 <!-- For texts with translations (that are not letters) -->            
               <title><!--Include title of original work here.--></title>
               <title xml:lang="eng"><!--Include translated title of original work here!--></title> 
            
````
If your comment above is meant to be your response to task # 4 on the assignment then please return to the [exercise](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/Exercises/TEIheader_exercise.md#step-by-step-process) and reread the task. You need to pick an element from the TEI Header section of the TEI guidelines that is not in the template file and write a short statement on what the element is for and why or why not we might use it for the Lili Elbe project.

**Comment by bossa12** [comment]
I find 'list' '/list' element groups haven't been used in our issue. This element can be used more specific like 'listEvent', 'listRelationships', 'listPerson'... These will give ideas about how the listed items related to each other and the traits those items share.

**Comment by bossa12** [comment]
@RJP43 hey Rebecca, I uploaded the TEI header file into the LiliForeword file, but how can I refer the file into this issue board?

**Comment by RJP43** [comment]
@bossa12 I see your file here - [LiliForeword_header.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/LiliForward/LiliForeword_header.xml). Well done! Thank you for uploading. In order to receive full credit, @Tatjanawj you will need to respond to @bossa12's statement above regarding the list element groups and write a statement so @bossa12 can respond to your statement before class.

**Comment by Tatjanawj** [comment]
> I find 'list' '/list' element groups haven't been used in our issue. This element can be used more specific like 'listEvent', 'listRelationships', 'listPerson'... These will give ideas about how the listed items related to each other and the traits those items share.

The element <encodingDesc> is also not included in our XML document. Usually this would put the text into context, which would have been helpful with this text. The foreword was written by Lili herself, which would have been interesting to know.
