### ISSUE TITLE
Let's Discuss Project Assignments

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#2]
The final projects for this class will incorporate a variety of tasks. All of the tasks utilize skills we built together during the month of February. While certain groups will have slightly more technical aspects of their final project than other groups, ALL GROUPS will be responsible for communicating via our class Issues Board - following out [best practices](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Working-in-GitHub#using-our-issues-board) - as well as uploading to & downloading from this GitHub repository. Below I have defined the other types of tasks different groups will be completing.   

# Task Types  

-  **Document Transcription**: As a minimal-tech task, those involved in document transcription will reference facsimile images of certain texts in order to transcribe the text seen in the image into a plain text (`.txt`) file or Google Doc with detailed comments describing document idiosyncrasies.    
- **Transcription Encoding**: If assigned this task, teammates will work with the project's encoding guidelines and the TEI Header template to construct an XML surrogate of the available transcription/translation of a given text. Encoders will be associating the project's new schema at the start of encoding; therefore, the final XML (`.xml`) file will need to be well-formed and valid.    
- **XML Corrections**: This task involves associating the new project schema to existing XML files and making corrections to the XML in order to make the XML valid and well-formed. Those working on this task will also be responsible for combining TEI Headers with the TEI Text from the existing XML.  Some XML correctors will be working closely with @ProfPLC to make content corrections to mis-transcribed/mistranslated text.   
- **HTML proofing**: Proofers will be using Hypothes.is to indicate content and processing mistakes seen once the various XML texts are transformed into HTML. Proofers will report errors using the Hypothes.is annotation tool and the class Issues Board, but will need to review input XML to determine if errors in HTML presentation are results of encoding mistakes or missing style transformations.    
- **Collation**: This task involves going through the narrative carefully, marking in A1 (the American first edition) where changes exist in the other editions and the typescript. This task entails working closely with @ProfPLC in order to make decisions on what to mark as a variant and why.  
Collation group 1 - (1 people) - paragraph by paragraph collation with @ProfPLC and @Tatjanawj  
Collation group 2 - (2 people) - scene/motif collation

# Available Texts  

## Danish materials:
[Danish Materials GitHub Project Board](https://github.com/RJP43/LiliElbe_EngagedLearners/projects/1)   
[Danish Archive Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive)   
  
**Lili Elbe to Maria Garland**  
four letters, 6 pages total  
XML corrections and HTML proofing (2 people)     
  
**Lili Elbe to Poul Knudsen  and  T. C. Thomsen to Hoyer**   
four letters, 6 pages total  
XML corrections and HTML proofing (2 people)    
  
**S. Thomsen to Harthern**
approx. 20 pages total  
XML corrections and HTML proofing (4 people)   
  
**Politiken articles** 
3 articles, 11 pages total  
XML corrections and HTML proofing (2 people)  
  
## German materials:   
[German Materials GitHub Project Board](https://github.com/RJP43/LiliElbe_EngagedLearners/projects/3)  
[German Archive Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive)   
  
**German letters 1 and 2, and the foreword**  
3 texts, 6 pages total  
XML corrections and HTML proofing  (3 people, including @Tatjanawj)  
   
## French materials:
[French Materials GitHub Project Board](https://github.com/RJP43/LiliElbe_EngagedLearners/projects/4)  
[French Archive Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive)   
  
**Allatini chapter**  
1 chapter, 14 pages total  
XML corrections and HTML proofing of the translation (2 people, readers of French)  
transcription of the original French version and encoding of transcription (2 people, readers of French)        
   
**Hirschfeld chapter**  
1 chapter, 6 pages total  
XML corrections, HTML proofing (2 people, readers of French)   
  
**"Vice Versa" from Voilà**   
4 issues, 8 pages total  
Transcription (2-3 people)

**Comment by JackieAlfarah** [comment]
For the Danish letters, my first choice is the Lili Elbe to Maria Garland letters. I am more comfortable with HTML proofing than XML corrections. 

Second option would be 
Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer, HTML proofing

**Comment by katebarrettmurphy** [comment]
1. German Letter 2 - XML corrections and HTML proofing
2. German Letter 1 - XML corrections and HTML proofing

**Comment by alicapati** [comment]
- I would like to work on XML corrections for the Danish materials, specifically S. Thomsen to Harthern.
- If not, I would also be interested in transcription for "Vice Versa" from Voilà.
Overall, I would like to work in XML corrections.
I wouldn't mind working with @skarrow ☺️

**Comment by jsteele1** [comment]
I would like to do a project with the least amount of tech stuff. First choice: "Vice Versa" from Voila, transcription. Second option: Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer, HTML proofing.

**Comment by skarrow** [comment]
1. S. Thomsen to Harthern
   - HTML proofing
2. "Vice Versa" from Voila
   - Transcription

I'd like to work with @alicapati

**Comment by dpedz** [comment]
1. Lili Elbe to Maria Garland, XML corrections
2. "Vice Versa" from Voilà, fine with any task

**Comment by nroyce** [comment]
I prefer to work in smaller groups due to my commute. I live in Bolingbrook so it's not easy for me commute to work closely with multiple group members of various schedules. I have no preference on who I work with but I have enjoyed working with @Katiegriggs24 

My preferences in order:
1. **Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer**
   a. HTML proofing
   b. XML corrections
2. **Lili Elbe to Maria Garland**
   a. HTML proofing
   b. XML corrections

**Comment by Katiegriggs24** [comment]
1.Lili Elbe to Maria Danish letter with xml corrections
2. Lili Elbe to Maria Danish letter with Html Proofing

**Comment by bcristiana** [comment]
I would love to work on any of the French Archive documents and be involved in any of the tasks.

**Comment by ElleBromer** [comment]
I would also like to work on the Lili Elbe to Maria Garland letters and doing the XML corrections.

I would also be interested in the Hirschfeld chapter

**Comment by wravindran** [comment]
i would like to be in the group of lili elbe to Maria Garland and do html proofing for my first choice.
For my second choice i would like to be in the group of lili elbe to poul knudsen for html proofing

**Comment by BMiller10** [comment]
German materials, XML or HTML proofing.

**Comment by schola0208** [comment]
1) Allatini Chapter,: XML corrections and HTML proofing of the translation (I could also do the other tasks on this chapter)
2) Hirschfeld chapter: XML corrections, HTML proofing (2 people, readers of French)

**Comment by bossa12** [comment]
1.  Vice Versa" from Voilà -Transcription 
2.  Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer - XML corrections and HTML proofing

**Comment by amccann2** [comment]
1. xml corrections// letters to maria garland 
2. xml corrections // thomsen to harthern 

I would like to work with @kschoen3

**Comment by kschoen3** [comment]
1. Letters to Maria Garland (XML corrections)
2. S. Thomsen to Harthern (XML corrections)

I wold like to work with @amccann2

**Comment by kklimek1** [comment]
1) I would like to work on S. Thomsen to Harthern, preferably XML corrections. 
2) The Allatini chapter, XML corrections. 

I am flexible though, I feel comfortable with most of the tasks, so if I can't get these two, I can work on anything else available!

**Comment by Samantha9899** [comment]
German materials xml corrections and proofing

**Comment by Dadelinee** [comment]
1) Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer
-xml corrections and proofing 
2) Lili Elbe to Maria Garland
-xml corrections and proofing

**Comment by amandallopez** [comment]
1. Hirschfeld Chapter  -- XML corrections, HTML proofing
2. "Vice Versa" from Voilà -- Transcription

**Comment by tinatiehen** [comment]
**1. Lili Elbe to Maria Garland** - XML corrections and HTML proofing
**2. Lili Elbe to Poul Knudsen and TC Thomsen to Hoyer** - XML corrections and HTML proofing

**I would like to work with @ekupchella**

**Comment by RJP43** [comment]
We have decided project teams and will be assigning each task via assigned project team issues by class on Tuesday, 3/12! It has been a pleasure teaching all of you. I am very much looking forward to working together on individual tasks.
