### ISSUE TITLE
Problem 4

### ISSUE THREAD

**Issue by joaquindavalosponce** [RJP43/LiliElbe_EngagedLearners#22]
Key: garlandM - Name: Maria Garland - No ID - Appears: 3 times
Key: Lili - Name: Lili Ilse Elvenes - ID lili - Appears: 3 times
Key: (ref) kj - Name: Kristin Jacobsen NO ID - Appears: 1 time
Key: (ref) mb - Name: Maiken Boysen NO ID - Appears: 1 time
Key: (ref) tnm - Name: Tyler Monaghan NO ID - Appears: 1 time
Key: NO KEY (?) - Name: Hr. Oberartz - NO ID - Appears: 1 time
Key: NO KEY (?) - Name: The chief physician - NO ID - Appears: 1 time

**Comment by RJP43** [comment]
@joaquindavalosponce please move your response to your team's issue - https://github.com/RJP43/LiliElbe_EngagedLearners/issues/18.  

Well done with this task otherwise! :tada:
