### ISSUE TITLE
BCristiana_Option2

### ISSUE THREAD

**Issue by bcristiana** [RJP43/LiliElbe_EngagedLearners#25]
**Option 2**
Kadji Amin wants to have his cookie and to eat it. In the 2015 movie *The Danish Girl*, based on an adaptation of Lili Elbe’s life narrative, *Man into Woman*, he sees an attempt by the mainstream media to conveniently falsify the transgender history, for both commercial and definitional purposes. To prove that this is the wrong narrative, and Lili Elbe the wrong person to inaugurate the pantheon of queer inspirational figures, Amin employs a varied set of conceptual tools and a suitably selected factual base for his arguments. He contends that the `glandular rejuvenation in the guise of sex transition therapy` (601) is the real drive of Elbe’s tribulations and connects the sex-centered dawn of the last century with a system of “racialized biopolitics and eugenics” (597) for which she serves as an illustration of biologically fit, normative femininity (601). 
For Amin, Lili’s death is an `emotional rescue` device and one of the narrative’s sins. Thus, her shortly lived womanhood unties cathartically the transgender identity from the pathological stigma, while it obscures the positivist belief at the time in biology as the remedy of all the ills that threaten the whites’ racial superiority. Discontented with a film that voids the past of its specificity in order to infuse it with the present day understanding of transsexuality, Amin commits himself the presentism fallacy. In judging Lili as interested rather in rejuvenation than in sex alteration, not only does he replace the effect with the cause, but expects from her a behavior that typifies the present acception of transgender, at a time when its conceptual awareness didn’t exist, much less the language to express it. The way he interprets it, the film asserts a linear determinism that links the problematic past of transsexuality with its present, within an endochronologic framework whose apparent simplicity conceals the `sexological and colonial forms of knowledge-power` (591) and whitewashes the `biopolitical eugenics` (594). Thus, Amin argues that Lili’s fictional memoir doesn’t belong to the queer `wrong body` narrative, but takes `the glandular conception of selfhood to its logical limits` (596). While Lili’s surgeries closely precede the Nazis’ rise power, and her surgeons’ careers become entangled for the better or for the worse with the state-enforced eugenic project, Amin substitutes again the subsequent for the antecedent and connects speculatively the source of her ovarian transplant with the forced sterilization program (601). He takes the next step and, in a twisted syllogism, links the ovarian transplant to the rejuvenation as part of the `efforts to direct reproduction` (598), and Lili’s case of sex reassignment surgery to the attempts to fix sexual degeneration and `restor[e] . . . ‘healthy’ sex polarity` (599). 
At times conflating this fictional memoir and its cinematic version, though the latter is one degree farther from the reality than the former, he criticizes a literary discourse with the tools of sociologist when, in yet another anachronistic fallacy, considers the transgenderism of both *Man into Woman* and *The Danish Girl* not intersectional enough because it does not deal with the `hierarchical structures of value and silent modes of normativity` (590). Yet he ignores the influence of Foucault’s systems of power-knowledge in the shaping and creation of the subjectivity, that is, the very mechanism at work in the repudiation of the scientific racism at the end of WWII. It is the French philosopher’s concept of genealogy as historical process subjected to contingent forces that he appeals to in analyzing the `relation between this past and contemporary transgender politics` (593), as opposed to the endochronological predictability. In this way, he can reveal inconsistencies and uncomfortable truths and demonstrate that `there is nothing presumptively innocent about the trans subject across time and place` (603). After advancing some very strong conclusions based on speculative conjectures only, in the end, he describes the genealogy that he advocates for as open to `multiple ramifications and often contradictory origins` (602). If now, as then, the biopolitics of transgenderism involves tensions engendered from the same `multiple systems of oppression and privilege` (602), maybe this study focuses on the wrong period and with the wrong tools.

**Comment by RJP43** [comment]
Whoops. As discussed in email, the response above has been added to the correct discussion issue.
