### ISSUE TITLE
Lili Elbe to Maria Garland : Jackie, Katie, Wagme

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#26]
hey there @JackieAlfarah @Katiegriggs24 @wravindran 👋  
  
Your team has been assigned the Danish-language letters from Lili Elbe to Marie Garland. As a team you will need to associate [the new project schema](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng) to each of these four letters:  
   
1. [19310616LEGarland.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310616/19310616LEGarland.xml)   
2. [19310724LEGarland.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310724/19310724LEGarland.xml)  
3.  [19310807LEGarland.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310807/19310807LEGarland.xml)  
4. [19310818LEGarland.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310818/19310818LEGarland.xml)   
  
Then you will need to correct the XML errors (in the entire file of each file - including errors found in the `<tei:header>` elements). Be sure to reach out via this issue if you hit any snags. Simply tag me - @RJP43 - and add the "help wanted" label to this issue.  
![screenshot highlighting help wanted label](https://user-images.githubusercontent.com/8645521/54369274-a2d2fc00-4643-11e9-8a83-c19196fce6bd.png)  If I do not respond within 48 hours with my 👀 reaction then please shoot me an email at `rparker3 (at) luc (dot) edu` and I will be in contact ASAP. 

After you have uploaded the valid and well-formed XML files in each of the letters' respective folders, tag me - @RJP43 - and add the "transformation ready" label to this issue.  I will then use our project's XSLT (eXtensible Stylesheet Language Transformation) and will respond to your team here in this issue with an HTML proofing link.   
  
From there your team will work to [HTML proof](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Proofing-HTML) each of the four letters -- reporting errors and design concerns regarding the HTML styling to me via this issue (tagging me and again using the "help wanted" label) and, otherwise, revising the XML where improper encoding has resulted in faulty HTML rendering.  As a reminder, you will use all of the materials in each of the four letters' folders (i.e. original transcriptions, facsimile images, etc.) to proof the HTML.
 
Once each of the four letters has been proofed @ProfPLC and I will inform your project team of next tasks or that your project contribution (well... at least this more "technical" aspect of it) is complete.  Please note the project and the training materials available on this repository are still in flux. This means that there might be moments where I need to inform your team of new updates that will require XML corrections or re-reading of lesson materials; therefore, please check this issue and the general [issues board](https://github.com/RJP43/LiliElbe_EngagedLearners/issues) regularly for alerts from me.   

**_Recent Update_**: We have moved away from using the MIWSchema.rng, and are now using our new schema - [LEDA_ODD.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng).  Please be sure you download this new schema and delete the old one from your computers.  We also now have a much more robust prosopography file listing all of the identified people and places in our project files. Please reference our [LEDA_Prosopography.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_Prosopography.xml) when trying to identify proper key attribute values.  Every xml:id attribute value in the file is a possible key attribute value that can be used in your XML files. We will be outputting an HTML transformation of this prosopography file soon and when we do I will be sure to inform your team via this issue.

**Comment by JackieAlfarah** [comment]
@katiegriggs24, @wravindran and I decided that I would do letter one, Wagme will do letter 2 and Katie will do letter 3. We will then come together and do letter 4.

**Comment by JackieAlfarah** [comment]
I associated the schema for letters 1 and 4 and uploaded them to the files. @RJP43 @wravindran @Katiegriggs24

**Comment by Katiegriggs24** [comment]
I assiciated the new schema to letter 3 and uploaded it. @RJP43  @wravindran @JackieAlfarah

**Comment by RJP43** [comment]
:eyes:  @JackieAlfarah @Katiegriggs24 @wravindran I see some faulty XML coming in. Please be sure you are not adding any XML elements not seen in our [teiHeader template](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/TEIHeader_Template.xml) or [encoding guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md). Let's try to schedule a team meeting to fix bugs 🐛.  
   
📆  I will be at the reference desk on the second floor of the IC from 9 AM to 1 PM tomorrow (3/21) and then I will be holding office hours in IC study room #219 from 1 PM until class time. I also have availability Friday morning before 1 PM as well as Monday before 11 AM, from noon until 2, or after 3 PM.  👋

**Comment by JackieAlfarah** [comment]
Is the faulty XML on letters 1 or 4?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by RJP43** [comment]
:eyes: @JackieAlfarah There is XML in all of the files that is wonky. I imagine you are all still correcting the schema validation errors, but I am worried there still might be some confusion. Anyone checking schema validation errors must correctly have the `.rng` schema file saved to their local computer within the same folder as the XML being validated and as a true `.rng` file.  I guess what I saw coming in was some corrections but other errors not corrected and I was worried that instead of working with a file checking the validation live that manual checking between the guidelines and the file was all that was really being done.  Either way, if any of you want to meet please let me know.

**Comment by RJP43** [comment]
@JackieAlfarah let's meet at noon tomorrow in IC 217.

**Comment by JackieAlfarah** [comment]
Sounds good. I have a class at 1, so I can stay until 12:40

**Comment by JackieAlfarah** [comment]
Hey Rebecca, what building is ic 217 in? I just transferred to Loyola this semester so I’m not sure of all the building names yet lol

**Comment by RJP43** [comment]
@JackieAlfarah the information commons is the big glass building attached to the library. Come in the front doors, using your Loyola ID, and up the stairs (or the elevator to the left). On the second floor, IC 217 is in the far right corner by the lake. I am here now so you will see me when you come around the corner towards classroom 216.

**Comment by JackieAlfarah** [comment]
Ok I’m coming now

**Comment by JackieAlfarah** [comment]
Hey, @Katiegriggs24 @wravindran. I met with Rebecca today to discuss the XML letter 1 in regards to errors that were firing on Oxygen, along with the next steps for the project. If you guys have any questions, I will try my best to answer. If i am not sure how to answer, I encourage scheduling a time during Rebecca's office hours to catch up and resolve any ongoing issues. Personally speaking, it helped me a lot!

**Comment by wravindran** [comment]
I have uploaded the xml with the associated schema for 2

**Comment by JackieAlfarah** [comment]
![Screen Shot 2019-03-26 at 3 06 44 PM](https://user-images.githubusercontent.com/47154947/55029737-d5341000-4fd8-11e9-9977-f758c822b522.png)  hey @RJP43 this salutations error came back up. I tried using the Letters Encoding Guidelines, but the error keeps firing. What could i do to correct it? We worked on one just like this earlier but I do not remember if we changed it to "salute" 
Thanks!

**Comment by RJP43** [comment]
:eyes: @JackieAlfarah remember the entire `<p>` element and the style attribute-value pair get removed in place for the `<salute>` element. Reference our changes to the translation div and [this section of the encoding guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#letters). Please let me know if you need further clarification.

**Comment by JackieAlfarah** [comment]
Hey @RJP43 you'll be in class today, right?

**Comment by JackieAlfarah** [comment]
Re-uploaded letter 4 XML to its folder with errors corrected. Labeled it ReadyForTrans

**Comment by RJP43** [comment]
@wravindran and I will meet today at 11 AM in IC Study Room 214

**Comment by JackieAlfarah** [comment]
I’m not on campus today, so I will most likely come tomorrow around 11:30

**Comment by RJP43** [comment]
@JackieAlfarah okay -- see you at the IC reference desk on the 2nd floor tomorrow.

**Comment by JackieAlfarah** [comment]
Hey Rebecca, I don’t think I will be able to make it tomorrow. My grandma needs me to take her to her doctors appointment. I won’t be on Campus until 12:45 and my class starts at 1.

**Comment by RJP43** [comment]
:eyes: okay @JackieAlfarah thanks for letting me know. Best wishes to you and your grandma ❤. I have some availability tomorrow and Monday if you want to reschedule :calendar: - simply check my office hours calendar and let me know. Otherwise, I will touch base with your team on Tuesday in class.

**Comment by JackieAlfarah** [comment]
Sounds good. Thanks!

**Comment by JackieAlfarah** [comment]
just uploaded letter 1. Ready to transform

**Comment by Katiegriggs24** [comment]
I uploaded the letter three with corrected errors.

**Comment by RJP43** [comment]
@wravindran My apologies I have to cancel our meeting today. I am just in too much pain. Remind me of which letter you are working on and upload your latest version here on GitHub. I will take a look at your progress and report back on this issue with any questions/concerns or to let you know it all looks good. Thanks for hopefully understanding.

**Comment by wravindran** [comment]
Alright thanks rebecca. Hope you feel better.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Dadelinee** [comment]
Hey @JackieAlfarah @wravindran and @Katiegriggs24 ! Sorry to barge in on y'alls issue haha but I figured since we're on the symposium team together I could help you with any encoding stuff if you need while I wait for my documents to get transformed (unless I get put on something else but honestly I can try to balance out helping on the side too lol) Let me know if that's okay! Totally cool if you'd rather not lol. Oh, side note, I never got the group text from you yesterday, Jackie. If you maybe wanna try and send it again that'd be super rad! Thanks :^)

**Comment by JackieAlfarah** [comment]
Hey. Sorry I’ll resend the text now. My number is (708) 890-1181.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by JackieAlfarah** [comment]
I totally could have taken your number down wrong so that could be it lol

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by RJP43** [comment]
:eyes: @JackieAlfarah @Katiegriggs24 @wravindran please let me know which of the files, listed in my first comment, are transformation ready. If you are all transformation ready please mark this issue with the transformation ready label as described in my first comment. Thanks! 👍

**Comment by JackieAlfarah** [comment]
letters 1 and 4 transformation ready @RJP43

**Comment by JackieAlfarah** [comment]
https://github.com/RJP43/LiliElbe_EngagedLearners/labels/transformation%20ready

**Comment by Katiegriggs24** [comment]
letter 3 is transformation ready @RJP43 #

**Comment by wravindran** [comment]
I believe letter 2 is transformation ready @RJP43

**Comment by RJP43** [comment]
Thank you all for your hard work. 💟 I am closing this issue since all four of you are now working on Proofing HTML. Please see issue #44 for HTML proofing instructions.
