### ISSUE TITLE
Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer : Adeline

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#27]
hey there @Dadelinee and @nroyce  👋  
  
Your team has been assigned the Danish-language letters from Lili Elbe to Poul Knudsen and T. C. Thomsen to Hoyer. As a team you will need to associate [the new project schema](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng) to each of these four letters:  
   
1. [19310122LEKnudsen.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310122/19310122LEKnudsen.xml)   
2. [19310131LEKnudsen.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310131/19310131LEKnudsen.xml)  
3.  [19310306LEKnudsen.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310306/19310306LEKnudsen.xml)  
4. [00000000ThomsenTHoyer.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/00000000/00000000ThomsenTHoyer.xml)   
  
Then you will need to correct the XML errors (in the entire file for each file - including errors found in the `<tei:header>` elements). Be sure to reach out via this issue if you hit any snags. Simply tag me - @RJP43 - and add the "help wanted" label to this issue.  
![screenshot highlighting help wanted label](https://user-images.githubusercontent.com/8645521/54369274-a2d2fc00-4643-11e9-8a83-c19196fce6bd.png)  If I do not respond within 48 hours with my 👀 reaction then please shoot me an email at `rparker3 (at) luc (dot) edu` and I will be in contact ASAP. 

After you have uploaded the valid and well-formed XML files in each of the letters' respective folders, tag me - @RJP43 - and add the "transformation ready" label to this issue.  I will then use our project's XSLT (eXtensible Stylesheet Language Transformation) and will respond to your team here in this issue with an HTML proofing link.   
  
From there your team will work to [HTML proof](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Proofing-HTML) each of the four letters -- reporting errors and design concerns regarding the HTML styling to me via this issue (tagging me and again using the "help wanted" label) and, otherwise, revising the XML where improper encoding has resulted in faulty HTML rendering.  As a reminder, you will use all of the materials in each of the four letters' folders (i.e. original transcriptions, facsimile images, etc.) to proof the HTML.
 
Once each of the four letters has been proofed @ProfPLC and I will inform your project team of next tasks or that your project contribution (well... at least this more "technical" aspect of it) is complete.  Please note the project and the training materials available on this repository are still in flux. This means that there might be moments where I need to inform your team of new updates that will require XML corrections or re-reading of lesson materials; therefore, please check this issue and the general [issues board](https://github.com/RJP43/LiliElbe_EngagedLearners/issues) regularly for alerts from me.   

**_Recent Update_**: We have moved away from using the MIWSchema.rng, and are now using our new schema - [LEDA_ODD.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng).  Please be sure you download this new schema and delete the old one from your computers.  We also now have a much more robust prosopography file listing all of the identified people and places in our project files. Please reference our [LEDA_Prosopography.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_Prosopography.xml) when trying to identify proper key attribute values.  Every xml:id attribute value in the file is a possible key attribute value that can be used in your XML files. We will be outputting an HTML transformation of this prosopography file soon and when we do I will be sure to inform your team via this issue.

**Comment by nroyce** [comment]
Hi @Dadelinee! Let’s chat today in class about how to tackle this one together so we don’t do double work or distribute unevenly. My name is Nichole and I sit in the front row, middle of the classroom and I’m rocking purple hair currently. :purple_heart: :metal:

**Comment by Dadelinee** [comment]
@RJP43 I'm on the last error and I ran into a little problem. I tried following the letter structural encoding and I'm a little confused as to what this specific error means. Did I close an element in the wrong place? I noticed one of the divides has a comment that says "end closer original" but putting the closer element there fires up another error due to incorrect form I believe.  
![Screenshot (1)](https://user-images.githubusercontent.com/47280713/54662888-886aa980-4aad-11e9-9d5e-5047390f2cde.png)

**Comment by RJP43** [comment]
:eyes: @dadelinee upload your latest file and I will pull it in and see what the issue is in the hierarchy from my computer. Just a smidge hard to see from the screenshot. THANKS.

**Comment by Dadelinee** [comment]
@RJP43 Alright I uploaded it!

**Comment by RJP43** [comment]
:eyes: Thanks @Dadelinee. I have gone ahead and corrected your file. I commented on the correction that needed to be made here - https://github.com/RJP43/LiliElbe_EngagedLearners/commit/d5206c53baeafad21cea5c0085a97b7078a617aa#r32846617. Great work so far! 🎉 👍

**Comment by nroyce** [comment]
Hey @Dadelinee (and @ProfPLC and @RJP43)!

I apologize for missing class yesterday.  I had oral surgery :mask: :hurtrealbad: yesterday and was advised to take my meds and not drive anywhere for the day.  I hadn't anticipated that so I apologize.  Adeline, please let me know if you have assigned a portion of the assignment for me to complete since I was absent.  Otherwise I'll just have to go in and figure out what you've done and what still needs to be done. :cold_sweat:
See you tomorrow!! Stay dry! :umbrella:

**Comment by Dadelinee** [comment]
@nroyce That's okay! Sorry, I meant to put my idea here and then I forgot to once I started doing some other homework. Since I started the first letter, if you want to do the last two and I'll finish the first letter and do the second. Then once we're done with the .xml portion we can re-upload them here and let Rebecca know we're ready to move on to the HTML part!

**Comment by nroyce** [comment]
@dadelinee Sounds like a plan!

**Comment by RJP43** [comment]
📆 If either of you need to meet up with me, I will be at the reference desk on the second floor of the IC from 9 AM to 1 PM today (3/21) and then I will be holding office hours in IC study room #219 from 1 PM until class time. I also have availability Friday morning before 1 PM as well as Monday before 11 AM, noon until 2, or after 3 PM. 👋 Just let me know.

**Comment by Dadelinee** [comment]
@RJP43 Hey Rebecca! I won't be able to come to office hours today because I already have another appointment with another professor but I think my only confusion is adding in the `<signed>` element because each time I do it says the error "element not allowed here." Other than that, I'm pretty sure I have all the other errors fixed. But if you were able to figure out how to add the <signed> element, @nroyce I would love to know how you did it lol. I may be putting it in the wrong place but I though it goes next to Lili's name (but still outside of the persname element) since she's signing the letter right there.

**Comment by RJP43** [comment]
:eyes: @Dadelinee I just realized I was confused about your question because your comments were missing the tic marks around your `<signed>` element. So I didn't know what element you were talking about. I have added the tics into your comment above.   

As for the issue you were having I have implemented the correct encoding in your file (so simply re-download). Here is the correct encoding for your future reference:  
````
<closer>
     <salute>Your poor little friend</salute>
     <signed><hi rend="underline"><persName key="lili">Lili Elvenes</persName></hi></signed>
     <salute>A thousand kisses to <persName key="knudsenV">Vibeke</persName></salute>
     <signed><hi rend="underline"><persName key="lili">Lili</persName></hi></signed>
</closer>
````

**Comment by Dadelinee** [comment]
@RJP43 Ohhh okay that makes sense, sorry about that. I appreciate it, thank you!

**Comment by Dadelinee** [comment]
Hey @RJP43 I just uploaded the 19310131LEKnudsen.xml letter with the new associated schema and most of the fixed .xml. Although I ran into 2 problems. 1) I tried fixing the attribute value for "Loulou Lassen" and when I checked the prosopography, the value was "louLou" and that's how it's typed in the document, however, it still fires as an error in oxygen. I can't really find what's wrong with the code there. 2) There's a piece of code that highlights in the letter that something is underlined and the original code was `<p style="upsideDown">` and so initially I tried switching it to `<hi rend="UpsideDown">` since that's how the other markups in the letter were written, however the attribute value isn't valid. Is there another code I'm supposed to use for that that I'm missing? Thanks!
(I'm adding this after starting the 3rd letter)
I noticed there's some code `<div type="postscript">` to indicate that the following text was the PS portion of the letter, and I was curious if I follow the code under the "Additions" portion of the encoding guidelines (something like the `<add place="XXX" type="XXX" rend="XXX">` and filling in the appropriate values) or if there's another code I'm not seeing.

**Comment by RJP43** [comment]
:eyes: @Dadelinee do you have any availability to meet this week? 📆 I am available before 1 PM on Tuesday (3/26) and after noon (12 PM) on Wednesday (3/27). It may be that we need to add something to the schema to handle postscripts and upside down text, but I would like to review the files with you to be sure. In your above comment you say the text is underlined but the encoding says "upsideDown" so I am just a bit confused. As for the key for Loulou Lassen, I am not sure why that error is coming up so I will need to see it in the file to figure that one out too since he has an ID in our prosop. and schema.

**Comment by Dadelinee** [comment]
@RJP43 Sorry for late reply! Tomorrow (26th) I have an exam at 1pm so I might be spending the morning studying but I should be good to meet Wednesday afternoon since I have a lot of free time then.

**Comment by RJP43** [comment]
:eyes: @Dadelinee ... no worries and best of luck with your exam! I have reserved IC study room 218 from 11 AM to 3 PM. Other learners are stopping by at 11 and at 2:15ish so I should be open from noon to 2 PM if you want to come by. Let me know when I should expect you. If ya need to meet after 3 PM I can probably do that too but will need to reserve another room so just let me know. :+1:

**Comment by Dadelinee** [comment]
@RJP43 Thanks! And I should be good to meet at around 12:30 since my class gets out around 12:20 tomorrow (27th)

**Comment by Dadelinee** [comment]
@RJP43 For all the persName elements, are we also putting on the "source" and "synch" attributes as well? I just want to make sure I do that if we're supposed to.
Also, when tagging the `<seg>` elements, I know we're supposed to do it for anything that's translated and that includes the closer right? What about names in the closer (like Lili) because it's the same in both English and Danish and I'm not sure if I need to tag that as a `<seg>` element.

**Comment by RJP43** [comment]
👀 @Dadelinee for persName and placeName elements you use the key attribute -- the key attribute should match the xml:id attribute value on the person and place elements in the prosopography file. Check out this section of [the prosopography section of the encoding guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#prosopography-markup) for a more detailed description.  
  
 If it is just the persName within the paragraph of parent::element then you don't need the seg markup. Re-reading [the section on translation segmentation in the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#translation-segmentation) should help. Also, @Samantha9899 has pretty good example files (letters 1 & 2 as well as the Foreword) in the [German Archive](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive) you can reference.

**Comment by Dadelinee** [comment]
@RJP43 I looked at the encoding guidelines and for the header of letters I have a question. In the guidelines it says it usually includes the place and date the letter was written, however it also says they should be wrapped in `<placeName>` and `<date>` elements, yet, when I look at example xml, like for German letter 2, I see that the headers for the place don't have a `<placeName>` element and the dates have the `<date>` element with the "when=" attribute. Should I add the `<placeName>` element to my letters for the heading? And should I also put the "when=" attribute on the date?

**Comment by RJP43** [comment]
:eyes: @Dadelinee, Yes please add both the when attribute and placeName elements to any mentioned places. The German Letters mentioned in my last comment are good examples of the letter and translation structure within the `<text>` elements ... I haven't had the chance to review @Samantha9899's `<teiHeader>` elements yet.

**Comment by Dadelinee** [comment]
> 👀 @Dadelinee, Yes please add both the when attribute and placeName elements to any mentioned places. The German Letters mentioned in my last comment are good examples of the letter and translation structure within the `<text>` elements ... I haven't had the chance to review @Samantha9899's `<teiHeader>` elements yet.

@RJP43 Okay, sorry, hopefully last question for today, do you also want me to add the "when" attribute to the dates in TEI header too or just the dates within the letter itself?

**Comment by RJP43** [comment]
:eyes: @Dadelinee just within the letter ... thanks!

**Comment by Dadelinee** [comment]
@RJP43 "Ullstein" and "Drei Masken" need key IDs in the prosopography! They're publishers mentioned in the letter (letter 19310131)
Also need to add .docx to THoyer letter

**Comment by RJP43** [comment]
:eyes: @Dadelinee when those publishers are mentioned are they referred to more like a publishing house or as individuals? We have entries for both of these names in the place section of the prosopography because elsewehre they have been referred to as the publishing houses. If it seems these are individuals then we will need to adjust the keys elsewhere. I will bring this issue up to @ProfPLC. If it turns out these are not individuals being referenced then you will change your `<persName>` elements to `<placeName>` elements and use their key IDs from the prosop listPlace section. Thanks! 👍

**Comment by Dadelinee** [comment]
![66B5DA63-B22B-4096-83B9-0D2888B96647](https://user-images.githubusercontent.com/47280713/55629818-c3413280-5779-11e9-9dc4-9c6f8fc3867b.jpeg)
@RJP43 This is the portion of the file they’re mentioned in. It looks like she’s mentioning them as specific people but it’s possible I’m reading it wrong. She could be referring to them as the whole entire publishing company and my original thought may have been that they were simply just people

**Comment by RJP43** [comment]
👀 @Dadelinee thanks for giving me the snippet. I will check with @ProfPLC today and get back to you. 👍

**Comment by Dadelinee** [comment]
@RJP43 awesome thanks! I think the thing that was making me think they were people were Kristin’s notes since they said “name of a publisher” and I’m not sure if she meant a person or a whole publishing house, if that helps

**Comment by kejcat** [comment]
What I remember from doing the translation is that Drei Maiken and Ullstein are publishing companies.

**Comment by Dadelinee** [comment]
@kejcat Oh okay that makes sense I’ll be sure to switch them, thank you!!

**Comment by RJP43** [comment]
:eyes: Thanks @kejcat. And sounds good @Dadelinee -- thanks!

**Comment by Dadelinee** [comment]
Hey @RJP43 ! Just wanted to check if you had time to add the word document for the THoyer letter yet? Thanks! Other than that, pretty sure every other letter is ready

**Comment by RJP43** [comment]
Wow 😮 great job getting through all three of those other letters! 🎉 You are certainly an XML proofing power house. ✊ 🏠 I am so sorry I kept forgetting to add the word document for the ThomsenTHoyer letter. 😟 I have just now added it [here](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/00000000/00000000ThomsenTHoyer%20Revised%20(11.20.18).docx). 💛   

Once you get through this last letter. Be sure have to walk through the XML proofing workflow detailed on issue #35 - like getting the teiHeader completely updated and checking every person/place encoded in the original are also encoded in translation and vice versa - for each letter. Then, you should mark your issue with the "Transformation Ready" label.  I will be in class on Tuesday to touch base. Thanks! 👍

**Comment by Dadelinee** [comment]
@RJP43 Ah, no worries, thank you! And I actually just realized in the Hoyer letter, he mentions this place called "Havnegade" which is like some waterfront promenade in Denmark (when I searched it) but I don't see it in the prosopography and I wasn't sure if that was intentional or not

**Comment by RJP43** [comment]
:eyes: @Dadelinee I did a [quick search of "Havnegade" on the repo](https://github.com/RJP43/LiliElbe_EngagedLearners/search?q=Havnegade&unscoped_q=Havnegade) and it looks like that in the other instances where this place is mentioned it has not been marked. If you could please put it in a placeName element, but leave off the key attribute that would be fine. Thanks 👍

**Comment by RJP43** [comment]
@Dadelinee I am about to upload the HTML proofing views for all four of your letters. In the meantime, please spend your time working on your blog post. Thanks for your amazing work! 🎉 👍 Please see issue #44 for HTML proofing instructions.
