### ISSUE TITLE
 S. Thomsen to Harthern : Sophie, Aliana

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#28]
hey there @skarrow and @alicapati 👋  
  
Your team has been assigned the Danish-language letters and diary entries from S. Thomsen to Harthern. As a team you will work to combine the following XML files into a single XML file titled `19310615ThomasSHarthern_combo.xml`: 
  
1.  [19310615ThomasSHarthern.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19310615/19310615ThomasSHarthern.xml)   
2.  [19211922ThomsenSdiaryentries.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19211922/19211922ThomsenSdiaryentries.xml)  
3. [19241200UnknownUnknown.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19241200/19241200UnknownUnknown.xml)   

In addition to combining those files and uploading the new file to the [19310615 folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/19310615), your team will need to associate [the new project schema](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng) to your new XML file as well as this [19311221ThomsenSHarthern.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19311221/19311221ThomsenSHarthern.xml) file.

Then you will need to correct the XML errors (in the entire file for each file - including errors found in the `<tei:header>` elements). Be sure to reach out via this issue if you hit any snags. Simply tag me - @RJP43 - and add the "help wanted" label to this issue.  
![screenshot highlighting help wanted label](https://user-images.githubusercontent.com/8645521/54369274-a2d2fc00-4643-11e9-8a83-c19196fce6bd.png)  If I do not respond within 48 hours with my 👀 reaction then please shoot me an email at `rparker3 (at) luc (dot) edu` and I will be in contact ASAP. 

After you have uploaded the valid and well-formed XML files in each of the letters' respective folders, tag me - @RJP43 - and add the "transformation ready" label to this issue.  I will then use our project's XSLT (eXtensible Stylesheet Language Transformation) and will respond to your team here in this issue with an HTML proofing link.   
  
From there your team will work to [HTML proof](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Proofing-HTML) each of the two letters -- reporting errors and design concerns regarding the HTML styling to me via this issue (tagging me and again using the "help wanted" label) and, otherwise, revising the XML where improper encoding has resulted in faulty HTML rendering.  As a reminder, you will use all of the materials in each of the two letters' folders (i.e. original transcriptions, facsimile images, etc.) to proof the HTML.
 
Once each of the two letters has been proofed @ProfPLC and I will inform your project team of next tasks or that your project contribution (well... at least this more "technical" aspect of it) is complete.  Please note the project and the training materials available on this repository are still in flux. This means that there might be moments where I need to inform your team of new updates that will require XML corrections or re-reading of lesson materials; therefore, please check this issue and the general [issues board](https://github.com/RJP43/LiliElbe_EngagedLearners/issues) regularly for alerts from me.   

**_Recent Update_**: We have moved away from using the MIWSchema.rng, and are now using our new schema - [LEDA_ODD.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng).  Please be sure you download this new schema and delete the old one from your computers.  We also now have a much more robust prosopography file listing all of the identified people and places in our project files. Please reference our [LEDA_Prosopography.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_Prosopography.xml) when trying to identify proper key attribute values.  Every xml:id attribute value in the file is a possible key attribute value that can be used in your XML files. We will be outputting an HTML transformation of this prosopography file soon and when we do I will be sure to inform your team via this issue.

**Comment by RJP43** [comment]
:eyes: @skarrow and @alicapati let's meet today during team time to discuss the uniqueness of this letter.

**Comment by skarrow** [comment]
We're planning on meeting all together as a group next Wednesday the 27th in the IC at 11ish @RJP43 

Tomorrow @skarrow and @alicapati are planning on meeting around 11:20ish in the IC to get started the best we can

**Comment by alicapati** [comment]
![Screen Shot 2019-03-19 at 3 19 56 PM](https://user-images.githubusercontent.com/47360918/54639095-917e5b00-4a5a-11e9-9ceb-8dad84b5dd37.png)

@RJP43, for this XML file, are we also combining it into the large document, or is it going to be a separate file that we have to associate the schema with ❔

**Comment by RJP43** [comment]
@alicapati Your team has two XML files that will need schema association and will be eventually turned into two separate HTML pages (for proofing). The first file is the combo file bringing together the three numbered files in my first comment. The second file is the [19311221ThomsenSHarthern.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/Danish_archive/19311221/19311221ThomsenSHarthern.xml).

**Comment by RJP43** [comment]
:eyes: @skarrow, @alicapati - Do you want me to schedule to join you during your meetings in the IC tomorrow and next week?

**Comment by skarrow** [comment]
@RJP43 if you could come next week that would be great!

**Comment by RJP43** [comment]
👀 @skarrow, @alicapati - No problem! I have reserved IC study room 218 from 11-1 on Wednesday, 3/27. I imagine we won't need the full two hours but figured best to reserve the space as long as possible. See you all then if not sooner.  👋 👍 


As a reminder, I will also be available at the IC reference desk today (3/21) and every Thursday from 9 AM to 1 PM and then from 1 PM until class time in IC room 219 just in case any of you need assistance sooner.

**Comment by skarrow** [comment]
@RJP43 @alicapati and I noticed there is not attribute ref for Matthew Gallagher (someone who prepared out photos) in the prosopography

**Comment by skarrow** [comment]
Also, we were wondering about Marianne Olholm prosopography ref key as well.

**Comment by skarrow** [comment]
Just kidding... I think we're doing it wrong...

**Comment by skarrow** [comment]
we still don't know Marianne Olholm's, Taylor Brown's, Nikolaus Wasomen's prospography ref key. We took the old TEI header and associated the new LEDA_ODD.rng schema, and corrected what we could. @alicapati uploaded the new TEI header to the document awaiting proofing.

**Comment by RJP43** [comment]
:eyes: @skarrow I hope I answered your inquiries regarding team member IDs here on the issue #35 regarding the project doc updates - https://github.com/RJP43/LiliElbe_EngagedLearners/issues/35#issuecomment-476646163.   
  
We can take a closer look at the updated TEI header @alicapati uploaded when we meet tomorrow at 11 AM in IC 218. The following are my first reactions to the files uploaded (but again we can delve into this more in depth when we meet):  
  
_The separate TEI header files in your team folder(s) were created simply as part of the class's learning process in February; however, your team's task is to add the updated TEI header info to the final XML file(s) that will be turned into HTML. So the corrected encoding and the updated TEI headers should be in a single file for each of your team's texts. Also, please note that the entire structure of the teiHeader template has changed in the latest update so you will need to copy from the template and then fill in the information - please see issue #35 for more detailed instructions._

**Comment by skarrow** [comment]
In the 19211922 document there is a letter with the name Else in it. Does Else have a persName key?

**Comment by skarrow** [comment]
In the 19211922 document there is a letter with the name Else in it. Does Else have a persName key?
@RJP43

**Comment by skarrow** [comment]
UPDATE: We have added the 19211922 translated english diary entries to the combo.xml

**Comment by RJP43** [comment]
:eyes: @skarrow I will need to get back to you with regard to "Else".

**Comment by skarrow** [comment]
@RJP43 We were wondering for the TEI header do we put the entire file numerical value as the date or just the last 6 letters?

**Comment by skarrow** [comment]
@RJP43 do we place the whole <person> attribute for the TEI header? Or is the xml id: the same as the `key=` in the encoding? 

Ex. do we place this for Sigurd Thomsen in the TEI header

`person xml:id="wegenerS" source="historical" synch="#nephew">
               <persName>Sigurd Wegener Thomsen</persName>
               <note><persName key="wegenerE">Einar Wegener</persName>'s nephew; son of
                     <persName>Christiane Wegener Thomsen</persName>, Einar's sister</note>`

or just this in the TEI header for who wrote the letter in our folder

`<persName>Sigurd Wegener Thomsen</persname>`

**Comment by skarrow** [comment]
@RJP43 we couldn't find a ref id for Maiken Boysen

**Comment by RJP43** [comment]
:eyes: Hi,@skarrow! 👋 I have added the key `boysenM` for Maiken Boysen and the key "else" for Else in the prosopography. They will be in the next schema update later today. So just add those keys to your persName elements and they will no longer be read with the new schema. 

As for Sigurd Thomsen in the TEI header, anywhere a person from the prosopography is mentioned you need to wrap their name in persName and add the key attribute with the attribute-value from the matching person and xml:id in the prosopography. So in your encoding, any mention of Sigurd should look like this: `<persName key="wegenerS">Sigurd Wegener Thomsen</persname>`. Please see [the Prosopography section of the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#prosopography-markup) for a better understanding of the key and xml:id linking.   

With regards to your letter's title in the teiHeader in the date element just include the numbers in from your XML filenames. So the `19310615ThomasSHarthern_combo.xml` letter will get `<date when="1931-06-15">19310615</date>` in the title element of the teiHeader. 

Hope this helps. Please reach out with any additional questions! Thanks. 👍

**Comment by alicapati** [comment]
@RJP43 Hey, Rebecca! Sophie and I are finishing adding the Danish letters into our combined file, but cannot find a persName tag in the prosopography for "Moder".

Also, we associated the new schema with our document and it still is not accepting the persName attribute, "else," for Else 🙁

**Comment by skarrow** [comment]
@RJP43 We have finished uploading all the Danish and English entries and we are ready to meet with you to make sure we did it right and to learn to encode the notes. Yay!

**Comment by RJP43** [comment]
@skarrow @alicapati Great work! 🎉 Seriously! Getting that multi-file encoding wrangled was a complicated task, and I am grateful for your time spent on it! Are you still working through the rest of the XML proofing workflow detailed on issue #35 - like getting the teiHeader completely updated, checking every person/place encoded in the original are also encoded in translation and vice versa, etc. If you are done with all of that you can mark your issue with the "Transformation Ready" label. I will add the `"else"` key later today -- this is her prosopography entry and once I re-run the schema the error should go away:
````
<person xml:id="else" source="historical">
               <persName source="#danishSupp">Else</persName>
               <persName>Else Wegener</persName> <!--RJP:2019-04-08: need to verify with @ProfPLC this would be Else's last name-->
               <note><persName key="wegenerS">Sigurd Wegener Thomsen</persName>'s sister and <persName key="lili">Lili</persName>'s niece</note>
</person>
````  
As for "moder" I believe this word means mother in Danish (@kejcat can you verify? ✔️). If so is there any indication of whose mother. Perhaps @kejcat can take a look or one of you could email @ProfPLC asking if she can identify whose mother is being mentioned. We just need to be sure "moder" actually needs a new key or and not an alternative name for someone that already has an entry in the prosopography. Thanks 👍 

As for setting up a meeting,  📆 I will be in class tomorrow and have some availability after class. I also have availability before noon on Wednesday and as always I will be at the IC reference desk on the second floor from 9 AM -1 PM on Thursday. Let me know what works for you both. Again, many thanks! 💯

**Comment by alicapati** [comment]
@RJP43 Hi, Rebecca! There are only a couple things left in our file that are firing as errors, which are: `<persName key="">Else</persName>` and `persName ref=""<!-- Name of Proofer --></persName>`. I just assume that Else has yet to be added to the prosoprography, which is fine! ☺️ Since our document has also not been transformed or proofed yet, should @skarrow and I just leave them blank, which will continue firing as an error in the schema? 

**Thank you!**

**Comment by RJP43** [comment]
:eyes: @alicapati Yes those get left until you proof the document then you or whoever does the proofing will go back in and add the correct resp information.   

@skarrow @alicapati  Please add the "else" key to every persName around Else. If there are no other problems, please remove the "help wanted" label and add the "transformation ready" label. Thanks! 👍

**Comment by RJP43** [comment]
Thank you both for your hard work on these files. I am closing this issue since you both are now moving on to HTML proofing. Please see issue #44 for HTML proofing instructions. 💟
