### ISSUE TITLE
German Letters and Foreword : Samantha

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#30]
hey there @Samantha9899 👋  
  
Your team has been assigned the German-language letters 1 and 2 as well as Lili's Forword. As a team you will need to associate [the new project schema](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng) to each of these XML files:  
   
1. [German_letter1.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/German_letter1/German_letter1.xml)  
2. [German_letter2.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/German_letter2/German_letter2.xml)  
3. [LiliForeword.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/archivalMaterials/German_archive/LiliForward/LiliForeword.xml)
  
In addition to associating the schema, we are asking that you help us clean up our filenames for both of the German letters. Please change `German_letter1.xml` to `19320309KellerHLE.xml` and `German_letter2.xml` to `19310627LEKellerH.xml`.  The foreword filename should remain the same. 

Then you will need to correct the XML errors (in the entire file for each file - including errors found in the `<tei:header>` elements). Be sure to reach out via this issue if you hit any snags. Simply tag me - @RJP43 - and add the "help wanted" label to this issue.  
![screenshot highlighting help wanted label](https://user-images.githubusercontent.com/8645521/54369274-a2d2fc00-4643-11e9-8a83-c19196fce6bd.png)  If I do not respond within 48 hours with my 👀 reaction then please shoot me an email at `rparker3 (at) luc (dot) edu` and I will be in contact ASAP. 

After you have uploaded the valid and well-formed XML files in each of the letters' and foreword's respective folders, tag me - @RJP43 - and add the "transformation ready" label to this issue.  I will then use our project's XSLT (eXtensible Stylesheet Language Transformation) and will respond to your team here in this issue with an HTML proofing link.   
  
From there your team will work to [HTML proof](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Proofing-HTML) each of the two letters and the foreword -- reporting errors and design concerns regarding the HTML styling to me via this issue (tagging me and again using the "help wanted" label) and, otherwise, revising the XML where improper encoding has resulted in faulty HTML rendering.  As a reminder, you will use all of the materials in each of the two letters' and the foreword's folders (i.e. original transcriptions, facsimile images, etc.) to proof the HTML.
 
Once each of the two letters and the foreword have been proofed @ProfPLC and I will inform your project team of next tasks or that your project contribution (well... at least this more "technical" aspect of it) is complete.  Please note the project and the training materials available on this repository are still in flux. This means that there might be moments where I need to inform your team of new updates that will require XML corrections or re-reading of lesson materials; therefore, please check this issue and the general [issues board](https://github.com/RJP43/LiliElbe_EngagedLearners/issues) regularly for alerts from me.   

**_Recent Update_**: We have moved away from using the MIWSchema.rng, and are now using our new schema - [LEDA_ODD.rng](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_ODD.rng).  Please be sure you download this new schema and delete the old one from your computers.  We also now have a much more robust prosopography file listing all of the identified people and places in our project files. Please reference our [LEDA_Prosopography.xml](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/LEDA_Prosopography.xml) when trying to identify proper key attribute values.  Every xml:id attribute value in the file is a possible key attribute value that can be used in your XML files. We will be outputting an HTML transformation of this prosopography file soon and when we do I will be sure to inform your team via this issue.

**Comment by Samantha9899** [comment]
I have associated the new schema with German letter 1 and uploaded it to the files.

**Comment by BMiller10** [comment]
@RJP43 are we going to ever work on German Letter 3?

**Comment by Samantha9899** [comment]
For the German letter 1 one of the errors is `<resp>Translation on <date when="?"> January to March 2018</date> by</resp>` how would we put the date in the key since it is from January to March and not one specific day? @RJP43 @katebarrettmurphy

**Comment by BMiller10** [comment]
In the element `type=""`, it only allows for `original` and `translation`. We are not sure how to apply this to paragraph distinctions, like the header or the body.

**Comment by RJP43** [comment]
:eyes: hi team @katebarrettmurphy, @Samantha9899, and @BMiller10 👋

There are several questions posed above and some I worry will be too confusing to answer over this issue or email. I would like for your team or each of you individually to meet with me as soon as possible to get you back on track.    
   
📆 I will be at the reference desk on the second floor of the IC from 9 AM to 1 PM today (3/21) and then I will be holding office hours in IC study room #219 from 1 PM until class time. I also have availability Friday morning before 1 PM as well as Monday before 11 AM, noon until 2, or after 3 PM. 👋 Just let me know when works best for each of you. Thanks!

**Comment by RJP43** [comment]
👀 hi team @katebarrettmurphy, @Samantha9899, and @BMiller10 👋 Please let me know when one or all of you can meet. 📆 I have availability before 1 PM on Tuesday (3/26) and after noon (12 PM) on Wednesday (3/27). I will also be available at the reference desk on the second floor of the IC from 9 AM to 1 PM on Thursday (3/28).

**Comment by Samantha9899** [comment]
@RJP43 @BMiller10 @katebarrettmurphy Tuesdays and Thursdays I don't get out of class until 12:45 so I don't think that'll work for me and Wednesday I will be done with class at 2pm so if you're available I can meet.

**Comment by RJP43** [comment]
👀 @Samantha9899 I can meet you after your 2 PM class. I have reserved IC study room 218 from 11 AM to 3 PM on Wednesday (3/27). I have put you in for the 2:15 slot on [my office hours calendar](http://bit.ly/2MdASUn). See you there!

**Comment by katebarrettmurphy** [comment]
I can meet there at 3ish if you guys will still be around. @Samantha9899 @RJP43

**Comment by RJP43** [comment]
:eyes: @katebarrettmurphy I have extended my office hours to be available until 4 PM 📆 so that we can have time to meet. Thanks for responding!! 👍  See you tomorrow!

**Comment by Samantha9899** [comment]
I have associated the schema to the Lili forward and uploaded it.

**Comment by katebarrettmurphy** [comment]
Hi, @RJP43 I am not going to be able to meet anymore because I'm getting back later to campus than I expected and also forgot about an interview I have at 5:15 pm today. I am so sorry and just wanted to let you know, so you weren't waiting up for me.

**Comment by RJP43** [comment]
:eyes: @katebarrettmurphy okay thanks for letting me know. I am worried about the progress on your team's tasks and I think it is only fair to @Samantha9899 for you and @BMiller10 to find a time to meet with me individually before your next in-class team time. @Samantha9899 has made some significant progress for your team on German Letter 1 and Lili's Foreword. I asked her to hold off on making any more corrections on German Letter 2 so you (@katebarrettmurphy) and I had a file to work on if you would have been able to make my office hours today. Can either of you (@katebarrettmurphy and @BMiller10) meet me tomorrow during my reference desk shift (9 AM - 1 PM on the second floor of the IC) or my office hours (1-2 PM in IC 219)? If not, we will need to touch base on Monday or Tuesday before class.

**Comment by Samantha9899** [comment]
I have finished the German letter 1 tei header and I believer it's ready for transformation. @RJP43

**Comment by Samantha9899** [comment]
I have made corrections to German letter 2 and uploaded it. It may also be ready for transformation. Please let me know if there is something to fix or if it is okay. @RJP43

**Comment by Samantha9899** [comment]
I have made corrections to the Foreword and have filled in the tei header with the information provided. The photography information is still not filled since the document says "don't know" for some parts. I have uploaded the document and it may be ready for transformation. @RJP43

**Comment by RJP43** [comment]
:eyes: @BMiller10 and @katebarrettmurphy the two of you are being reassigned to new tasks since @Samantha9899 has a handle on these files. Please be in contact with @ProfPLC and me about your new assignment.  Additionally, the two of you should be in contact with @ProfPLC via email to discuss your progress in the course. 📑 

@Samantha9899 I will be transforming your letter later today (if not, tomorrow) and will be alerting you with instructions to complete the HTML proofing ASAP. Thanks for your hard work and patience! 👍 

See you all in class on Tuesday. 👋

**Comment by RJP43** [comment]
@Samantha9899  I am about to upload the HTML proofing views for the German Letter 1 & 2 as well as Lili's foreword. In the meantime, please spend your time working on your blog post. Thanks for your hard work! 🎉 👍 Please see issue #44 for HTML proofing instructions.
