### ISSUE TITLE
"Vice Versa" from Voilà : Jade, Ran, Danica, Elle

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#33]
hey there @jsteele1, @bossa12, @dpedz, and @ElleBromer 👋   

_This issue was re-worked on April 6th to invite Elle on to this project team and to correct the transcription process. **Please only continue working on transcriptions after re-reading this issue!**_
  
Your team has been assigned the French-language "Vice Versa" issues from _Voilà_. As a team, you will transcribe the original text from the facsimile images for the five issues. Each issue's images are available in their respective folders of the larger [ViceVersa folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa). **_Please note only the text of the Vice Versa story should be transcribed - ignoring any of the surrounding Voilà text (i.e. advertisements, other articles)._ We ask the text be transcribed (character by character; paying close attention to accents and original font styles found in the print rendition!)**

Transcriptions can be done in Microsoft Word and then uploaded to the correct folder in your team's [ViceVersa folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa). You will notice in each issues' folder I have created a starter `.docx` file with the correct filename. If you choose to transcribe in Microsoft Word please begin by downloading the base file and upload your file overtop of that file as you progress. 

Transcriptions can also be done in the following Google Docs for each issue: 
[ViceVersa_Issue1](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing)  
[ViceVersa_Issue2](https://docs.google.com/document/d/18jYrI9yMUdIuaB67H6AeI-2hhMe0e08HDufIrc1Njfg/edit?usp=drivesdk)
[ViceVersa_Issue3](https://docs.google.com/document/d/1YNDriY9_GEbaCSCXJlk5ZfAAhTXApPLGDdvjltTIBig/edit?usp=sharing)   
[ViceVersa_Issue4](https://docs.google.com/document/d/1rvPMf2WsIUjqZP_vxHUvnU1aXkp1gf9X5DQDOSNBw4o/edit?usp=sharing)  
[ViceVersa_Issue5](https://docs.google.com/document/d/1zfJFxtcq1qnVpY8VddpACiQDs5SnjLWsmHMiZ30d9YQ/edit?usp=sharing)  

Transcribing in either Microsoft Word or Google Docs is fine as long as your partner (if you have one on your specific issue) is aware of where you both are working -- so as to not upload over eachother's files. Also you must include accents -- if you are more comfortable adding special characters in Word then use Word. To insert special characters in Google:  
1. At the top, click Insert and then Special characters.
2. Find the character you want to insert: search for base character (i.e. e for é), pick from categories, enter the character's Unicode value, or in the box on the right draw the character.
3. To add a character to your file, click it.

**When transcribing please keep the following in mind:**

- You must transcribe titles and section titles with proper formatting (e.g., bold, italics, or caps)
Make sure you capture all accents and special characters (e.g., é, ä, ê) 

- Indicate paragraphs with indentations as in the article (not spaces or numbers)

- Transcribe the article's page numbers at the end of each page's transcribed text, following the last line of the page

- Transcribe all captions for images at the end of the transcription for each page following this format: 
![ViceVersa_example_ImageCaptions](https://user-images.githubusercontent.com/8645521/55676219-e4974100-5895-11e9-9506-23d0624dbd48.png)

- Indicate any comments/questions that arise while transcribing in square brackets, highlighted in yellow, and with your initials  (as seen in the above example).   

***  

I have gone through and edited [ViceVersa_Issue1](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing) so it can be used as an example of our expectations. 

**Here are the new assignments:** 
[Issue 1](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue1): images 10,11 -- Transcribed by @bossa12 and @dpedz, Revised by @RJP43, Needs to be proofed by @jsteele1 for accents, em dashes, and hyphenation removal.    

[Issue 2](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue2): images 12,13 -- Transcription started by @dpedz, Needs to be revised by @dpedz according to [Issue 1 Example](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing)     

[Issue 3](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue3): images 14, 15 -- Transcription started by @jsteele1, Needs to be revised by @jsteele1 according to [Issue 1 Example](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing)    

[Issue 4](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue4): images 14 (1934), 15 (1934) -- Transcription to be led by @ElleBromer    

[Issue 5](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue5): images 1934 PDF -- Transcription to be led by @bossa12

**Comment by dpedz** [comment]
Hey @bossa12

So @jsteele1 and I have talked in class how we're gonna tackle the project. We decided that everyone will do 2 images each and then we will work on the last image together. 

**Some background info**
 We currently have 2 issues available to us and we will eventually have 4 total. Issue 1 has 5 images and Issue 2 has 2 images. 

Please pick out 2 images of your choice and state what issue it comes from and the number. 

@RJP43 For the google doc, can we have mutiple transcriptions on one doc or do we have to have separate docs for each image?

**Comment by dpedz** [comment]
I'll also be doing images 11 and 12 from Issue 1. 

**Edit** I'll be doing image 14 from Issue 2.

**Comment by RJP43** [comment]
:eyes: @dpedz whichever suits you and your team is fine with me. Please include all links on this issue board to any Google hosted documents and give share access to me using my gmail (listed above).

**Comment by jsteele1** [comment]
I will be working on images 14 and 15 from Issue 1 and Image 15 from Issue 2

**Comment by RJP43** [comment]
:eyes: Will your team be using one Google doc for each issue? That probably makes the most sense. Please provide links here on this issue! I also encourage someone on your team to regularly download a .docx version of your transcription files and upload them into your team's [ViceVersa Folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa).

**Comment by dpedz** [comment]
@RJP43 We haven't talked about that yet, but I'll discuss it with the others when we have team time.

**Comment by bossa12** [comment]
I'll do the two images from issue 3 and image 10 from issue1

**Comment by bossa12** [comment]
my gmail: ranzh.410@gmail.com

**Comment by dpedz** [comment]
@RJP43, So @bossa12 and I talked in class, we decided to do a main google doc and combine all of our transcriptions per issue. Those documents have been shared with you! 

@jsteele1 Since there is a new issue added, there are 9 images in total. Please pick one more picture and comment your gmail down below so I can add you to the documents. 

**For everyone** 
When you're writing your transcriptions, please make sure they don't share the same page as another transcription. This is for organization purposes. 

The timesheet where we record our hours can also be found on the document labeled "ViceVersa_Issue1", please don't delete it!

**Comment by RJP43** [comment]
Here are the Google Doc links shared with me: 
[ViceVersa_Issue1](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing)  
[ViceVersa_Issue2](https://docs.google.com/document/d/1YNDriY9_GEbaCSCXJlk5ZfAAhTXApPLGDdvjltTIBig/edit?usp=sharing)  
[ViceVersa_Issue3](https://docs.google.com/document/d/1rvPMf2WsIUjqZP_vxHUvnU1aXkp1gf9X5DQDOSNBw4o/edit?usp=sharing)   

Thanks! Please take notes on this issue sharing any text being added that is not a direct transcription of the text seen in the facsimile images. For example, I see in one of the files someone is using (P#) pseudo-markup to indicate paragraph numbers. I am fine with your group adding pseudo-markup as long as you all are consistent with one another.

**Comment by jsteele1** [comment]
My email is jadesteele7@gmail.com

**Comment by dpedz** [comment]
@RJP43 Will issue 4 be posted soon?

**Comment by RJP43** [comment]
@dpedz @jsteele1 @bossa12 My apologies! I have just been informed by @ProfPLC and Emily that I had placed three issues into one file. Please adjust according to the following issue divisions and share new Google Doc links with me.  

[Vice Versa - Issue 1](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue1)    
[Vice Versa - Issue 2](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue2)  
[Vice Versa - Issue 3](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue3)    
[Vice Versa - Issue 4](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue4)  
[Vice Versa - Issue 5](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/ViceVersa/ViceVersaIssue5)

**Comment by dpedz** [comment]
New Issue assignments 

Issue 1: 10,11 > Ran, Danica
Issue 2: 12,13 >Danica, all
Issue 3: 14, 15 > Jade
Issue 4: 14, 15 > Danica, Jade
Issue 5: "1934" image > Ran

**Comment by dpedz** [comment]
**Places** 
- Passy (Issue 1: 11)
- Allemagne (Germany) (Issue 1:11)
- Berlin (Issues 1,2,4: 11,12, 14)
- Carpi beach (la plage de Carpi) (Issue 3: 12)
- Balgencie (Issue 2: 12)
- municipal theater (Issue 2: 12) 
- cinema (Issue 2: 12)
- cafe (Issue 2: 12)
- paris (Issue 2: 12)
- la loire (Issue 2: 12)
- copenhague (Issue 2: 12) 
- dresde (Issue 4: 14)
- le jardin (Issue 4: 14)
- paris (Issue 4: 14)
- hotel (Issue 4: 14)
- LA CLINIQUE FÉMININE DE DRESDE (Issue 2, 4: 12,14)
- la salle d'operations (issue 2)
- les cabinets de consultation (issue 2)
- beaux-arts (issue 2)
- Salon d’Automne (issue 2)
- petite ville du Loriet (issue 2)
- chez un docteur (issue 2)
- versailles (issue 2)
-  le corridor de l’Hôtel des Réservoirs people (issue 2)


**People**
- Grete (Issues 1,2: 11,12)
- Lili (Issues 1,2, 4: 11,12,14)
- Andreas (Issues 1,2,4: 11,12,14) 
- Elena (Issues 1,2: 11,12)
- Werner Kreutz (Issues 1,2,4: 11,12,14) 
- Niels Hoyer (Issues 1,2,4: 11,12,14)
- Jean Tempte (Issue 2: 12)
- Claude Lejeune (Issue 2: 12)
- M. Rene (Issue 2: 12)
- Cupidon (Issue 2: 12)
- Iven (Issue 2: 12)
- l’infirmière (Issue 4: 14)
- le médecin (issue 2)
- docteur (issue 2)
- elena (issue 2)
- ernesto (issue 2)

**Comment by dpedz** [comment]
[Image 13 issue 2.pdf](https://github.com/RJP43/LiliElbe_EngagedLearners/files/3025145/Image.13.issue.2.pdf)

We'll be working on the last image together! I tried my best to equally divide the sections. There are 3 sections, please pick the section you'd like to do.

**Comment by RJP43** [comment]
> **Places**
> 
> * Passy (11)
> * Allemagne (Germany) (11)
> * Berlin (11,12, 14)
> * Carpi beach (la plage de Carpi) (12)
> * Balgencie (12)
> * municipal theater (12)
> * cinema (12)
> * cafe (12)
> * paris (12)
> * la loire (12)
> * copenhague (12)
> * dresde (14)
> * le jardin (14)
> * paris (14)
> * hotel (14)
> * LA CLINIQUE FÉMININE DE DRESDE (14)
> 
> **People**
> 
> * Grete (11,12)
> * Lili (11,12,14)
> * Andreas (11,12,14)
> * Elena (11,12)
> * Werner Kreutz (11,12,14)
> * Niels Hoyer (11,12,14)
> * Jean Tempte (12)
> * Claude Lejeune (12)
> * M. Rene (12)
> * Cupidon (12)
> * Iven (12)
> * l’infirmière (14)

:eyes: @dpedz Please go back and edit your comment above holding this list of people and places to indicate which Issue these names are linked with. You can edit a comment by clicking on the three dots to the right of the reaction smiley face (both sit in the top right corner of your comment). Thanks 👍

**Comment by dpedz** [comment]
@RJP43 I have already finished image 12 in issue 2 before @ElleBromer  was added onto our project.

**Comment by RJP43** [comment]
:eyes: @dpedz You never shared your document with me via Google or uploaded a copy of your work to GitHub. You also did not communicate here on your team's issue that you made progress with issue 2. If you do not stay in communication with me I cannot help you or confirm with @ProfPLC the work being completed. @ElleBromer @jsteele1 @dpedz @bossa12 I have once again revised this issue and adjusted the assignments since @dpedz has recently informed me she started transcription of issue 2. Please see my first comment on this issue for your new assignments. Thanks! 👍

**Comment by dpedz** [comment]
@RJP43 I thought I shared the document with the group, my bad! The document is now shared.

**Comment by RJP43** [comment]
@dpedz okay thanks for sharing. :+1: I went ahead and added @ProfPLC and Emily to the file (as I have for all of the other Google Docs). ✅ I backed up a copy of your issue to your file folder here on GitHub as well. ✅ Be sure to read thru my first comment and adjust your document accordingly. Thanks for your hard work! :tada: :heart_decoration:

**Comment by dpedz** [comment]
@RJP43 Names and places list is on a google doc and is shared with you and was revised to the correct format. Our group decided that this would be more convenient to have the list on google docs.

**Comment by RJP43** [comment]
Thanks @dpedz 👍 Here is a quick link to that file you've called ["Names and places list"](https://docs.google.com/document/d/1QeXhtBjfeGUkhoYNlsQhKeMARLzwSrg6q0gCXs0sOwE/edit?usp=sharing)

**Comment by cmccraw** [comment]
Hi, @dpedz @jsteele1 @bossa12 @ElleBromer ! I'm helping @RJP43 organize some of our GitHub files. Check the commits in each folder to see specifics, and feel free to use version control to access any files that were deleted in error. Here's the updates for each Issue folder:

**Issue 1**
n/a

**Issue 2**
- removed blank/outdated .docx files
- renamed "vice versa image 12 and 13 issue 2.docx" to "ViceVersa_Issue2.docx" [same file content, new name]
- **be sure that this file is backed up on [the Google Doc](https://docs.google.com/document/d/18jYrI9yMUdIuaB67H6AeI-2hhMe0e08HDufIrc1Njfg/edit?usp=drivesdk) !**

**Issue 3**
- updated ViceVersa_Issue3.docx [back-up file] to include most recent content from Google Doc

**Issue 4**
- updated ViceVersa_Issue3.docx [back-up file] to include most recent content from Google Doc
- **see Becca's example in[ Issue 1](https://docs.google.com/document/d/1sP4DY6lqbrCNcNPCEZd8sFStZ295o8fjA_oTkoDdOEw/edit?usp=sharing) for how to format images **

**Issue 5**
- Google Doc + .docx file are blank
- PDF needs to be converted to JPEGs?

Y'all rock! Let me or Becca know if you have any questions :) :)

**Comment by jsteele1** [comment]
I have finished my portion of the project and added my part to the names and places list
