### ISSUE TITLE
Collation : Tatjana, Anais, Tina, Elizabeth

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#34]
hey there @Tatjanawj, @anais-turiello, @tinatiehen, @ekupchella 👋  

Your teams have been assigned to collation work. Materials you will need are on Sakai/Resources/Project Assignments/Collation Work.
  
@tinatiehen, @ekupchella: You will fill out and proof the spreadsheets on your assigned chapters according to the samples and Thursday’s class lesson (3/14). You will need the collated versions of A1 and D1/TR (both available in the same Sakai folder).  
  
@Tatjanawj and @anais-turiello: You will begin filling in the G1 column on the spreadsheet for Chapters 00-05 on Sakai (Sakai/Resources/Project Assignments/Collation Work/Sample Collation).

**Comment by RJP43** [comment]
# @RJP43's In-Class Notes on Collation  
  
A collation is an ordered, systematic comparison of various versions or "witnesses" of a single work. 

For _Man Into Woman_, we have six witnesses: A1, B1, D1, G1, TS, TR  
  
Base Text: All collations have a base text (a text the others are compared to); For MIW our base text is A1.  

Possible ways to collate MIW: Collation by Paragraph, Collation by scene, Collation by theme or motif 
We're collating, intially anyway, by paragraph.     
  
Process Done Already: Numbered every paragraph in every chapter/section of each edition.

**Comment by RJP43** [comment]
:eyes: Hey team, I have created a folder for you to upload backup copies of the collation  spreadsheets into - [collationMaterials](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/collationMaterials). While Google offers adequate version control and space for collaboration we on the LEDA project practice the model of [Lots of Copies Keep Stuff Safe (LOCKSS)](https://www2.archivists.org/glossary/terms/l/lots-of-copies-keep-stuff-safe) in taking  such important steps (as backing up on GitHub) towards project sustainability and preservation.

**Comment by ProfPLC** [comment]
A shout out to @anais-turiello  and @Tatjanawj: do you need help from @tinatiehen and @ekupchella  when they finish collating D1/TR?  They have about four more chapters to collate, you have about fifteen. Please pick up the pace a bit and reach out for help, from Anna, Tina, and/or Elizabeth.

**Comment by RJP43** [comment]
Hi team 👋 @ekupchella @tinatiehen @anais-turiello @Tatjanawj @ProfPLC , 

In preparation for the Weekend of Excellence Symposium this weekend @cmccraw and I have worked together with @gloriousgeneralist (LUC's digital services librarian who is helping develop the LEDA website) and  Nick Wasmoen (LEDA digital editor) to bring you this live demo of the editions' **chapter one collation** -- http://bit.ly/LEDA_collationTest.  
  
Please note this demo is very much a ⚠️ work in progress 🚧 . When presenting this demo it is important for you to keep in mind there are 🛠 broken features and 🐛 buggy aesthetics that will be ironed out 👚  before launch. As always constructive feedback is welcome. 👍 💟

**Comment by RJP43** [comment]
@cmccraw is backing up the XML behind the VM Collation here - https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/collationMaterials

**Comment by tinatiehen** [comment]
Elizabeth and I finished our collation project on April 22nd, 2019.
