### ISSUE TITLE
XSLT assistance outreach -- arbitrary attributes added  

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#36]
**Issue:**   
at `//*` in output file - `A1_paranumber.xml` - there are arbitrary attributes added that are not on the `descendant::*` elements of the input file - `A1.xml`.

**Help request:**  
Is this a namespace related issue? How do I suppress these auto/default attributes from appearing after running my `numberingParagraphs_MIW_A1andB1.xsl` (a TEI XML to TEI XML identity transform)? 

Files are in the [sandbox](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/sandbox/XSLT_help). Thanks for any advice/assistance.

**Comment by RJP43** [comment]
@ebeshero @djbpitt @wendellpiez -- Sorry to bother you all during this busy part of the semester/year, but if you get a chance to look at this I would greatly appreciate any advice. Thanks!

**Comment by djbpitt** [comment]
@RJP43 I think this might be <https://www.oxygenxml.com/forum/topic10110.html>

**Comment by RJP43** [comment]
Huzzah! 🎉 Many thanks, @djbpitt!
