### ISSUE TITLE
Lili's IDs in Allatini

### ISSUE THREAD

**Issue by bcristiana** [RJP43/LiliElbe_EngagedLearners#37]
@RJP43 , hi! This is to remind you that, in Allatini chapter, Lili is consistently referred to as  "Lily" and, at least once, as "Lily Wegener". Also, I need instructions about how to encode to manuscript's cover page. Hopefully, this is the right way to do it.

**Comment by RJP43** [comment]
:eyes: @bcristiana Thanks for posting this issue. I have just now [added the additional name for Lili to the prosopography](https://github.com/RJP43/LiliElbe_EngagedLearners/commit/3bcddde189e9d24978ac7d260a9314a5d9a252e4) and it will be in our latest schema when I run it later today.   

I will attempt to get back to you later today or over the weekend regarding the encoding of the title page.

**Comment by bcristiana** [comment]
@RJP43 , thank you.
