### ISSUE TITLE
Coding segments

### ISSUE THREAD

**Issue by kejcat** [RJP43/LiliElbe_EngagedLearners#39]
I am putting in coding for segments the Sanheden article. Should headlines be included as segments? I thought yes but wanted to check. Thanks.

**Comment by RJP43** [comment]
:eyes: @kejcat if the text has a translation then it gets segmentation (😆) ... please let me know if the `<seg>` markup causes any schema validation errors. Thanks! 👍

**Comment by kejcat** [comment]
Thank you. So far, so good. The <seg> codes seem to be working OK.
