### ISSUE TITLE
Sanheden article 

### ISSUE THREAD

**Issue by kejcat** [RJP43/LiliElbe_EngagedLearners#41]
Becca,
Do you have any time to meet tomorrow (Wed.)? I’m almost done with my coding, and I have a fair number of questions best handled in person. 
Thank you!
Kristin

**Comment by RJP43** [comment]
:eyes: @kejcat I am available after 12 (noon). I work in systems 10-11, and I am meeting with an engaged learner in the IC from 11-12. When can you meet?

**Comment by kejcat** [comment]
I'm planning to come to campus late morning to pick up my graduation gown and do some work. Why don't you tell me when you've had a chance to eat lunch after your 11 a.m. meeting, or we could meet somewhere at noon for lunch and consultation? My only conflict is a meeting at 2 at Arriva Dolce.

**Comment by RJP43** [comment]
@kejcat I also need to pick up my gown so let's meet in Damen around noon and decide from there if we want cafeteria food or something on Sheridan.

**Comment by kejcat** [comment]
I’ll meet you outside the MPR where we pick up our gowns.

**Comment by kejcat** [comment]
@RJP43 the encoding guidelines are missing the image/figure markup. Here is an example from my file: 
````
<figure xml:id="i00">
<figDesc><hi rend="bold">Nowadays, you can expect anything. The other day my cousin (Fætter) came up to see me. He had become my female cousin (Kusine) since I saw him last.</hi></figDesc>
<note source="#kj">A man in striped pajamas is sitting up in a bed. A woman with short hair, dressed in an elegant pantsuit, sits at the end of the bed smiling at the man. A lit candle is on the bedside table. The cartoon is signed A.R. CANE.</note>
</figure>
````

**Comment by RJP43** [comment]
@kejcat I am trying to revise the encoding guidelines to reflect the correct coding for articles. Could you upload your most recent version from our meeting yesterday so I can reference it? Many thanks in advance! 💟

**Comment by kejcat** [comment]
I just uploaded SanhededArticle.xml, prosopography for Sanhede article.docx, and Sanheden article Post Review (4.2.19). I uploaded the last file because I made some copy editing changes. Kristin

**Comment by RJP43** [comment]
Thanks, @kejcat 💟. After working with @zothman, yesterday, and revising the [Politken articles](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/Politiken) structures these are the changes I am making in the encoding guidelines regarding the `<div rend="head">` for all articles:   
````
<div rend="head"<!--text that appears before headlines; could include title and date-->
   <p>
      <title><!--name of newspaper/mag/journal, if included in facsimile image otherwise delete--></title>
      <date when="yyyy-mm-dd"><!--exact transcription of date, if included in facsimile image otherwise delete--></date>
   <p>    
</div>
````
The `<seg>` markup would go within each of the title and date elements if the text has a translation. Please let me know if you get any errors and as always reach out with any questions. ✅ 👍 Did we schedule another meeting? 📆

**Comment by RJP43** [comment]
> https://github.com/RJP43/LiliElbe_EngagedLearners/issues/41#issuecomment-479613702  
  
I have added a section to the encoding guidelines detailing how to correctly encode ["Figures, Photos, Illustrations, Images](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#figures-photos-illustrations-images). Thanks for the reminder! 🎉

**Comment by RJP43** [comment]
I have just now updated the prosopography to include all of your additions. Thanks for those! They will be live in the schema later today. 🎉

**Comment by kejcat** [comment]
I just realized I never responded to your question about another meeting. Do you have any time Tuesday after noon, Wednesday after 2, or Thursday noon-3? Kristin

**Comment by RJP43** [comment]
📆 :eyes: @kejcat I am available noon until the EL class time at 2:30 on Tuesday. I have availability for either of the other days later in the evening like closer to 6 PM or I could get together before noon on Wednesday _(tho that is a less-preferred option for me personally)_. As for Thursday I am at the IC reference desk from 9 AM to 1 PM if you want to come during the last hour of my shift _(which I have been granted permission by the librarian on duty to invite LEDA team members for tech. assistance anytime during my lib. shifts)_ and then we could grab a study room for more time until I have to go to the EL class at 2:30.   

Let me know. Thanks! 👍

**Comment by kejcat** [comment]
How about Tuesday at 1? If that works, where would you like to meet? Thank you! Kristin

**Comment by RJP43** [comment]
Let's meet in Crown on the 4th floor in the lobby once you get out of the elevators. That way I can go right to class from there. Thanks!

**Comment by kejcat** [comment]
Sounds good. Kristin

**Comment by kejcat** [comment]
````
<note type="translator" source="mo" xml:id="comment_3">K. K. (Karl Kristian)
                        Steincke was a prominent social democrat. From 1929 he was the minister for
                        social affairs and he is probably best known for being behind the social
                        reform of 1933 which is often seen as the beginning of the Danish welfare
                        state. The reference here may be to the police commissioner's protection of
                        Steincke's 1920 book, The Future's Social Welfare (Fremtidens
                        forsørgelsesvæsen) in which he advocated for the sterilization of
                        "nonentities" or persons with non-normative sexual proclivities. The journal
                        seems to be condemning Mellerup for supporting Steincke’s writing on such
                        scandalous topics while criticizing, if not censoring, this journal. So now
                        they are going after <persName key="hasselbalchS">Hasselbalch</persName> for publishing Wegener’s scandalous story.</note>
````
KEY FOR STEINCKE: steinckeK

**Comment by kejcat** [comment]
````
<figure xml:id="i01">
                  <figDesc><hi rend="bold"><seg n="d26">I vore Dage kan man vente sig alt. Forleden kom min Fætter op og besøgte mig. Hun var blevet til en Kusine, siden jeg sidst saa hende.</seg></hi></figDesc>
                  <note source="#kj">A man in striped pajamas is sitting up in a bed. A woman with
                     short hair, dressed in an elegant pantsuit, sits at the end of the bed smiling
                     at the man. A lit candle is on the bedside table. The cartoon is signed A.R.
                     CANE.</note>
                  <!-- RENUMBER SEGMENTS STARTING HERE WITH D27. ALSO TRANSLATE NOTE INTO DANISH. TALK ABOUT TRANSLATING ALT TEXT INTO THE LANGUAGE OF THE ORIGINAL TEXT -->
               </figure>
````

**Comment by kejcat** [comment]
`<!-- KEJ 2019-02-21: I counted this as the third column in the article, but should it be column one for this page? -->`
We decided column numbering is based on the article as a whole rather than individual pages.

**Comment by kejcat** [comment]
Interesting gender assignment issue:

DANISH: Der viste sig ikke store Vanskeligheder ved Adoptionen. Ministeriet bevilgede gerne, at Fru Wegener adopterede Frk. Lily Wegener, og paa denne Maade blev den tidligere Ægtemand nu Datter i Huset hos sin forhenværende Hustru.

ENGLISH: No great difficulties appeared in connection with the adoption. The ministry willingly granted that Mrs. Wegener adopted Miss Lily Wegener, and in this way the former husband now became a daughter in the house of her former wife. 

````
 <p><seg n="d34">Der viste sig ikke store Vanskeligheder ved Adoptionen. Ministeriet
                     bevilgede gerne, at <persName key="wegenerG">Fru Wegener</persName> adopterede
                        <persName key="lili">rk. Lily Wegener</persName>, og paa denne Maade
                     <!-- KEJ 2019-02-21: The cartoon breaks up the text at this point in the second column. -->
                     blev <persName key="wegenerE">den tidligere Ægtemand</persName> nu <persName key="lili">Datter</persName> i
                     Huset hos <persName key="wegenerG">sin forhenværende
                  Hustru</persName>.</seg></p>
               <!-- Again, this could be really confusing. Should I tag tidliegere Aegtemand as Einar and Datter as Lili? -->
````

**Comment by kejcat** [comment]
We need to revise translator/editor comments due to double XML id's. 

````
<note type="translator" source="mo" xml:id="comment_comment1">
                     This
                        likely refers to Paragraph 184 in the criminal law of 1866 which was used in
                        other cases of literary censorship.</note>
             <!-- KEJ 2019-04-02: Did I construct the note correctly? -->
             be obscenity paragraphs. Perhaps
                     the truth is that the commissioner of police aided by <anchor
                        type="commentRangeStart" n="2"/><persName key="mellerup">Mr.
                        Mellerup</persName>, <anchor type="commentRangeEnd" n="2"/>
                     <note type="translator" source="Pamela Caughie" xml:id="comment_2"
                        <!-- BECCA IS INVESTIGATING. MARKUP NEEDS TO CHANGE. WE NEED TO PICK A NEW ATTRIBUTE -->
                        ><!-- KEJ 2019-04-02: What is Dr. Caughie's team ID? --> Einer Mellerup
                        was deputy police commissioner in Copenhagen from 1926.</note><!-- KEJ 2019-04-02: Did I construct the note correctly? -->
                     <anchor type="commentRangeStart" n="comment3"/><persName key="steinckeK"
                        >Steincke</persName>, <anchor type="commentRangeEnd" n="comment3"/>
             <!-- DOUBLE CHECK THAT XML ID FORMATTED COMMENT_4 BUT EVERYTHING ELSE IS JUST 4 WITHOUT THE PRECEEDING WORD COMMENT -->
                     <note type="translator" source="mo" xml:id="comment3"> K. K. (Karl
                        Kristian) Steincke was a prominent social democrat. From 1929 he was the
                        minister for social affairs and he is probably best known for being behind
                        the social reform of 1933 which is often seen as the beginning of the Danish
                        welfare state. The reference here may be to the police commissioner's
                        protection of Steincke's 1920 book, The Future's Social Welfare (Fremtidens
                        forsørgelsesvæsen) in which he advocated for the sterilization of
                        "nonentities" or persons with non-normative sexual proclivities. The journal
                        seems to be condemning Mellerup for supporting Steincke’s writing on such
                        scandalous topics while criticizing, if not censoring, this journal. So now
                        they are going after Hasselbalch for publishing Wegener’s scandalous story.
                     </note>that they cannot have their glance directed to other places than this
                     magazine.</seg></p>
````

**Comment by kejcat** [comment]
Ask those who have worked on the German text how they translated nouns that had been capitalized in German. Do we retain capitalization in English?

**Comment by RJP43** [comment]
@kejcat I spoke to @ProfPLC and she said you should absolutely correct those minor mistakes on Marianne's part in the translation like excluding an apostrophe, comma, etc. Thanks 👍

**Comment by RJP43** [comment]
:eyes: @kejcat I also spoke to @ProfPLC about whether or not we are retaining German/Danish noun capitalization in translation and she said no we regularize the capitalization in the English translation as one would expect it to be in modern English. Thanks 👍
