### ISSUE TITLE
Second Set of German Letters : Bennet, Joaquin, Samantha

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#42]
Hey there @BMiller10, @joaquindavalosponce, @Samantha9899 👋 

Please reference the [Facsimile Images](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/Spring2019_SecondBatchGermanLetters/FacsimileImages) and the [Transcription-Translation Word documents](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/Spring2019_SecondBatchGermanLetters/Translation_Transcription) when encoding these texts. All files for these texts will exist in the [`Spring2019_SecondBatchGermanLetters`](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/Spring2019_SecondBatchGermanLetters) folder.

**Specific assignments:**  
1931-12-28SchumannHoyer - @BMiller10   
1932-01-21HoyerSchumann - @joaquindavalosponce   
1932-06-30SchumannHoyer - @Samantha9899    
1932-07-16HoyerSchumann - TBD  

***

In order to complete XML encoding of these texts you will need to do the following for each letter: 

**_As always, please begin by downloading [the latest schema](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/LEDA_ODD.rng) as well as your text's images and transcription/translation `.docx` file._**
  
1. Go into oXygen and create a new XML file ➡️  in oXygen, click on the icon at top left that looks like a piece of paper with a folded corner (or go to File and New), type XML in the filter window, and click the Create button to launch a new XML document. -- instructions from our [`XML_Exercise`](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/Exercises/XML_exercise.md).  Be sure to save your new XML in the same folder as you downloaded the schema.  
2. Delete the contents of that new XML file and paste in the [TEI header template](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/TEIHeader_Template.xml) --- review the template filling in the applicable sections and removing sections that do not apply to letters. Be sure to use the TEI header spreadsheet and our list of `<respStmt>` team member IDs (both available on issue #35). 
3. Replace the `<text>` element with the ["Texts with Translations" encoding from the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#texts-with-translations).
4. Paste the [Letter text-type encoding from the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#letters) into each of the `<div>` elements. 
5. Paste the text of the original text from the Word document into the `<div type="original">` element. Be sure to paste interior sections of the letter into their respective, different sub-elements. Meaning you should paste the salutation text from the document into the first salute element and so on for each unique part of the letter. You will need to create `<p>` elements around each of the letter's body paragraphs after the first salute but within the `<div rend="body">`. 
6. Paste the text of the translation text from the Word document into the `<div type="translation">` element. Following the same instruction detailed in step 5. 
7. This is a good point to pause and upload your new XML to GitHub. Newly created `.xml` files should be uploaded to the [`Spring2019_SecondBatchGermanLetters`](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/Spring2019_SecondBatchGermanLetters) folder. XML files should be named the same as the corresponding Word documents except with the `.xml` file extension instead of the `.docx` extension. 
8. Once you have uploaded, please update this issue letting us know your progress and I will provide you with next steps.

**Comment by joaquindavalosponce** [comment]
Hey Rebecca,

I hope you had a great weekend. I am a little confused. The document I am getting from Github is a word document, doesn't it have to be a raw file so I can take the document to Oxygen?

Joaquin
________________________________

**Comment by RJP43** [comment]
:eyes: @joaquindavalosponce as described in my first comment above you are to create a new XML file then copy and paste the various parts of the letter (original and translation) into the appropriate encoding from the teiHeader and encoding guidelines. I tried to give a [step-by-step instructions](https://github.com/RJP43/LiliElbe_EngagedLearners/issues/42#issue-429377406) above so please try being very literal with each step and let me know if you are still confused. I have some availability this week to meet, but otherwise I will be in class on Tuesday and Thursday to help. 🆘

**Comment by Samantha9899** [comment]
@RJP43 The letter I am working on is written by "H. Schumann" and I don't see that name in the prosopography, what am I supposed to use as the key id?

**Comment by RJP43** [comment]
:eyes: @Samantha9899 Let's make the key schumannH and I will add him. Please let me know if you get any info. from the letter regarding his identity. Thanks :+1:

**Comment by Samantha9899** [comment]
@RJP43 I have finished with the steps given and uploaded the 1932-06-30SchumannHoyer

**Comment by RJP43** [comment]
@BMiller10, @joaquindavalosponce, @Samantha9899 once you have finished the first tasks of adding structural markup to your transcriptions/translations you can either begin working on your blog post or create a list of all the people and places listed in each of your files here in this issue. If you choose to work on the list of people and places please indicate in your comment below which text your lists correspond to. Thanks! 👍 Please reach out with any questions.

**Comment by Samantha9899** [comment]
**1932-06-30SchumannHoyer**
**People:**
Carl Reissner
Mr. Hoyer / Mr. Niels Hoyer
Mr. Einsiedel
Einar Wegener
Prof. Warnekros
Mr. Dr. Magnus Hirschfeld
Lili
H. Schumann

**Places:** 
Dresden
Institute for Sexual Science Berlin
Copenhagen

**Comment by BMiller10** [comment]
**1931-12-28SchumannHoyer**
People:
Harry Schumann
Niels Hoyer
Mrs. Diel
Lili Elbe

Places:
Copenhagen
Dresden
