### ISSUE TITLE
Proofing HTML - UPDATES!

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#44]
Hello HTML Proofers 👋  @JackieAlfarah @Dadelinee @bcristiana @alicapati @Katiegriggs24 @schola0208 @skarrow @kklimek1  @elenipamboukis @dpedz @wravindran @Samantha9899 

_For those that have marked and confirmed their documents are "transformation ready" I have now transformed your XML into HTML. You can locate all of the HTML versions of transformation ready XML in each of the different language archives._
**Danish HTML Proofing Views** = [Main Repo > ProjectDocs >archivalMaterials > Danish_archive > HTML_ProofingViews ](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/HTML_ProofingViews)  
**German HTML Proofing Views** = [Main Repo > ProjectDocs >archivalMaterials > German_archive > HTML_ProofingViews ](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/HTML_ProofingViews)   
**French HTML Proofing Views** = [Main Repo > ProjectDocs >archivalMaterials > French_archive > HTML_ProofingViews ](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/HTML_ProofingViews)  

_I have decided to group all of the HTML proofing views together because I do think it is important for anyone in the class to look over any of the HTML. Sometimes when working on a single document it is a bit more difficult to see mistakes that others first coming to a text will see right off the bat._     
  
## How to Proof HTML  
_Here is the step-by-step process of proofing HTML:_  
### Preparing to Proof
1. Download HTML file to be proofed. 
2. Have the XML of the transformed HTML open in oXygen. 
3. Have the facsimile images of the original document ready to view. 
4. Download  [`proofView.css`](https://raw.githubusercontent.com/RJP43/LiliElbe_EngagedLearners/master/ProjectDocs/archivalMaterials/proofView.css) in the same folder/space you downloaded the HTML. **The CSS must be in the same folder as the HTML in order for you to see the proofing styles.**  
5. Open the HTML file in oXygen and change the CSS link line to reflect the CSS is in the same folder as your HTML. Like this: 
 - In the `<head>` element you will see this line: `<link rel="stylesheet" href="../../proofView.css" />`  
- Change the above line to `<link rel="stylesheet" href="proofView.css" />`    
  
_I have left this step in the process so I can know which files when reuploaded to GitHub have had some proofing even if not extensive, complete proofing._     
  
###  Proofing HTML and Editing XML  
_I have decided to ditch the Hypothes.is method of proofing, for our class anyway, due to the difficulties of getting the HTML live online and this is why were are doing local proofing instead. Here are the steps to proofing locally:_    
1.  The only file you need open in oXygen, at this point, is the XML.  You will open the HTML in a browser. To open HTML in a browser you open the browser (Chrome, Firefox, etc.), hit CTRL (or Command on Mac) and the letter O. From there your file explorer (or Finder on Mac) will open and you can navigate to where you saved the HTML. Double click on the file to open.  
2. In each HTML proofing view I have listed what the various color coding and text styles indicate. You should first look over the file to be sure all parts of the document are rendering in the HTML. For example: if your file has a postscript does it appear in the HTML. 
3. The file used to transform the XML to HTML relies on the XML meeting the structural hierarchy indicated in the encoding guidelines and teiHeader template. Therefore if something is missing in the HTML it is likely miscoded in the XML. As you proof, you should correct the XML and re-upload the XML to GitHub as you make changes.   
4. If there is something off in the HTML where you cannot find what needs changing in the XML come back to this issue and report what you see in the HTML so we have a list of problems spots as the archive moves closer to launch.   
  
Please note besides changing the CSS link you will not make changes to the HTML. Once you have changed that CSS line I suggest you re-upload the HTML to GitHub and closeout of the HTML in oXygen. 
 
**PLEASE BE SURE TO UPLOAD THE XML, WITH YOUR PROOFING CHANGES, TO GITHUB.** I will be taking the XML with your corrections and re-transforming it several more times during the final proofing stages of the archive.  

If you are working on a team proofing HTML then you will need to determine with your group who will edit the XML when so as to avoid uploading your changes to the XML over your team-mates' changes. Anyone is able to proof any of the HTML. If you wish to proof HTML please let us know below which HTML file you are proofing so we do no get overlapping GitHub uploads.   
  
Thank you all for your continued hard work on this project and it has been a pleasure working with you all! 💟

**Comment by kklimek1** [comment]
@RJP43 Hi Rebecca! I brought this up in class, but our page numbers are showing up within our text.

**Comment by Dadelinee** [comment]
@kejcat Hey! I have a translating question. For Danish letter 19310122, in paragraphs 9 and 16, the Danish word for Mr. (I believe) is written as "Herr" in paragraph 9 but "her" in paragraph 16 and I was just curious which one was the correct form that way I can make that change in the Danish form. Thanks!

**Comment by RJP43** [comment]
@kklimek1 Thank you for pointing out the page number issue. 👍 I have now corrected this and pages should appear styled similar to the seg styling. Please let me know if you run into any other issues. Thanks!

**Comment by Dadelinee** [comment]
Hey @RJP43 ! Quick question, I noticed that the date for my letters only shows up in the HTML for the March 06, 1931 letter (The big "Lindevangen" portion at the top before the letter starts) but the other ones don't have that and I'm not sure how to make the coding in the .xml match that one so that the dates do show up once transformed in the rest of the letters.

**Comment by kejcat** [comment]
@Dadelinee You really are paying attention! I double checked the originals, and Lili spells it "Herr" with two r's in paragraph 9 and "Her" with one r in paragraph 16. Thanks for asking about it to make sure. Kristin

**Comment by RJP43** [comment]
The following XML documents are firing errors and/or not transforming correctly:
- 19310818LEGarland.xml    
- 19311221ThomsenSHarthern.xml  
- 19310615ThomsenSHarthern_combo.xml     
  
This either means something in the basic structural markup does not match the teiHeader template and/or the encoding guidelines OR I have to edit the transformation file to accommodate for something different in these files than a typical letter file. I imagine the latter is the case for `19310615ThomsenSHarthern_combo.xml`.  I will be reviewing these files closely in the next couple of days and reporting on why I think these files aren't transforming. In the meantime, please if you worked on the XML of these files be sure the hierarchy matches that in our templates. Thanks 👍

**Comment by RJP43** [comment]
@Dadelinee I think I just fixed the transformation mistake that caused the date issue you reported on above. Just let me know when you are done making initial corrections and I will re-run your files for us to double check this is resolved. 

@kejcat regarding Lili's use of "Herr" and "Her" -- are there two ways to spell Mr. in Danish or is one a spelling mistake on Lili's part? If this is a spelling error, which one is correct? @Dadelinee there will be a bit of markup to add around misspelled text if this is the case.

**Comment by kejcat** [comment]
I think the Herr/Her is a mistake. Herr is the word for Sir or Mr. and her means here in English. The abbreviation for Herr is Hr., but the original really looks like it is written as Her. Page one is 
![image](https://user-images.githubusercontent.com/47260893/56623684-e6cdff00-65fa-11e9-9969-b942b0d959c5.png) 

and page two is ![image](https://user-images.githubusercontent.com/47260893/56623645-c4d47c80-65fa-11e9-9667-9604dc7b397e.png).

**Comment by RJP43** [comment]
:eyes: @kejcat for the second instance, where we now collectively agree it seems to be a spelling error, would you as the translator of this document say it was more likely a misspelling for the abbreviation (Hr.) of the full word (Herr). @Dadelinee once we know what our translator recommends as the "regularized" word you will need to add the ["Correcting Errors from Print / Facsimile Images" markup](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#correcting-errors-from-print--facsimile-images) from the guidelines.

**Comment by elenipamboukis** [comment]
I am currently working on proofing the Allatini chapter please don't work on it right now!

**Comment by elenipamboukis** [comment]
After trying to follow directions, downloading Allatini chapter, and the CSS link, I have found some small problems- although I find it extremely difficult to find the parts of the text on the oxygen file after looking at the link. Here are the issues I found:
- I changed the capital S in Spanish in the English version to a lower case as it was lower case in the french version
-problem with pg 202 in french version f(10) where it says AParis not "A Paris" with the accent above the A ( not sure how to do that on this mac )
- Nordic is capitalized in f(13) in English version while it is not in the french version
- The english version has # in the f() while the french version does not.. I'm not sure if that is an issue or not
-Page 2014 french version f(14) there are separated dash marks - - instead of in the english version which has solid together dash marks
- f(15) has dash marks before dialogue while the english version does not
- Page 208 french version f(29) "Napoli!" or English version "Napoli." ( exclamation mark or period? ) 
I have re-uploaded the html, although there are minimal changes as I didn't know where to find them in the XML, but will do once I receive some help. Thank you!

**Comment by kejcat** [comment]
In answer to your question about whether the second "Her" is meant to be Herr or Hr., I would say that it most likely should be Herr. Lili makes numerous mistakes in other letters, writing in either haste or ill health or both. I think if she had meant to write Hr., we would have seen a period. Just my best guess.

**Comment by schola0208** [comment]
working on Hirschfeld right now. @RJP43, or anyone who may know the answer to this:  We have until midnight today right? or is it till the end of class? also, I pulled the xml from the project docs, french archive. thats where the last one is stored right?

**Comment by schola0208** [comment]
> working on Hirschfeld right now. @RJP43, or anyone who may know the answer to this: We have until midnight today right? or is it till the end of class? also, I pulled the xml from the project docs, french archive. thats where the last one is stored right?

re-uploaded file, i think the text is good to go, unsure of the tei header but I'll consult Cristiana to figure it out.

**Comment by kklimek1** [comment]
I'm currently working on Allatini!

**Comment by Dadelinee** [comment]
@RJP43 Heya! For the 19310122 letter, I put what I think is the correct coding for fixing the "herr" problem?  I uploaded the xml file so you can check it out. It's in seg d16 of the original letter towards the end of that segment.

**Comment by kklimek1** [comment]
Issues I've found with the Allatini text: 
- In the first paragraph there is a mention of "mon vieil ami," which in the Original had the key ID "MagreM" (and no ID in the Translation). Based on the context of the sentence, I kept the persName element, but got rid of the key ID, as I don't think the "old friend" is Maurice Magre. 
- I've added persName and placeName elements where they were missing.

**Comment by RJP43** [comment]
Hi @Dadelinee :wave: I am sitting here with @kejcat and we are about to get her started on proofing our Danish HTML files. She will need to go through all of the files at some point since she is our only Danish-speaking encoder; however, she is going to begin from the bottom of the file list here - [Danish_archive > HTML_ProofingViews](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/Danish_archive/HTML_ProofingViews). As she works her way up the list closer to the Knudsen files you have been working with she will check in here on this issue. @kejcat will be focusing on the Danish translation, Danish prosopography terms, translator notes, and other like information and we will need you to be proofing the English transcription, English prosopography terms, as well as the entire files basic hierarchical structure. Once you have moved through your originally assigned files we will get you started on the files @kejcat is working through now. Please reach out with any questions and be sure to tag both of us here on this issue as you finish your stage of proofing.  @kejcat will also be coming to this issue and letting us know when she has completed her level proofing for each text. Thank you both for your amazing work!

**Comment by elenipamboukis** [comment]
Currently working on Allatini!

**Comment by elenipamboukis** [comment]
Allatini Chapter-

ERRORS THAT NEED TO BE CORRECTED IN HTML 
(f#51) in english version says "Do you know, dear friend," whilst the French version says ", dear friend, " in translation

(f#58) in french version says "(because that's how she looked at her now)" in translation whilst the english version says "(for This Was how she thought of her now)." 

f(89) i'm not sure if the date is supposed to say "le 12 septembre 1931" or just "12 septembre 1931" 

f(79) French version is supposed to have an accent above the A in "At Dresden."

**Comment by Dadelinee** [comment]
Hey @RJP43 and @kejcat ! I did the proofing for the 19310122 letter (I didn't notice any issues) but I think that's the only one that's been updated proofing wise since I last fixed the xml of the others, correct?

**Comment by schola0208** [comment]
@RJP43 , I think we're done with Hirschfield, but I am not absolutely confident the final version is supposed to look the way it does. take a look when you have a minute and let me know

**Comment by cmccraw** [comment]
@RJP43 Proofed the Foreword for the German Letters, HTML and XML files are updated. I had a question about paragraph count/breaks— in the Foreword, g18 and g19 should be one paragraph according to the facsimile, as should g20 and g21. Wanted to check and see if combining the paragraphs in the XML file would throw off a paragraph count anywhere else (am so used to working with the editions, where it's a bigger deal!). Also wanted to make sure they weren't separated for a reason. 

Also, are we ignoring page breaks that occur within a paragraph? (In the Foreword, g20 has a page break mid-sentence). 

Thanks so much!

**Comment by cmccraw** [comment]
@RJP43 In the HTML, the "closer" for German Letter #2 English translation is not showing up (it's fine in XML). 

Otherwise, German Letters 1 + 2 are proofed.

**Comment by kejcat** [comment]
I just finished proofing 19310807LEGarland, and there was a lot to fix. I included the corrections I made in the HTML Proofing Spreadsheet (https://docs.google.com/spreadsheets/d/1d-tIQqdtcEGnDzsQoihkOH9H7JceLshsnrBRkQURU90/edit?ts=5ce41792#gid=0), and I uploaded the XML file to the Archival Materials folder, but I have a number of questions about issues I wasn't sure about. 

1) The date on the letter does not print in the HTML rendering. How do I fix that?
2) Should I encode <persName> in the salutation (Kære Veninde/Dear Friend) as Maria Garland, since Lil is encoded as a <persName> in the signature?
3) Venende is a feminine form of the Danish word for friend. Should I include that as a translator's note, or is it not relevant because Maria identifies as female?
4) One note says Editor and the other says Translator, though both were written by Maiken and me. Was this a choice by someone else, or should I change them both to Translator?
5) When I transcribed the letter, I included not just paragraph breaks but also line breaks. One of the changes I made in the XML was to correct the paragraph coding. Should I also put in line breaks to reflect the format of the original letter? 
6) When you mouse over the two notes, it says "Key ID: kreutz" and "Key ID: lil" rather than the person's name. Is this correct? 

How do I get a new HTML rendering so that I can see what my changes look like? Is that something I can do or that @RJP43 has to do?

This letter definitely needs someone else to go over it again. 

Thank you for your help!

Kristin

**Comment by kejcat** [comment]
I just looked at earlier posts of this issue and saw that @RJP43 wrote earlier in the month that I should focus on "the Danish translation, Danish prosopography terms, translator notes, and other like information." I went beyond that in my questions above. Should I pull back and just focus on Danish-language issues? Thanks. Kristin

**Comment by kejcat** [comment]
Mouse over does not display Maria Garland as a <persName>. I changed <seg> codes so that they wrap the text to see if that would help: <seg n="d01">Kære Fru<persName key="garlandM"> Maria Garland</seg></persName>. Original is <seg n="d01">Kære Fru<persName key="garlandM"> Maria Garland</persName></seg>. I'm not sure if this is correct, though. I also included this issue in the Archival Materials--HTML Proofing Spreadsheet.

**Comment by kejcat** [comment]
My apologies. The above doesn't make sense because I forgot to type it so that the codes would print. I will batch all my questions for this letter and put them in one comment. Kristin

**Comment by kejcat** [comment]
Here are the issues I've found with 19310724LEGarland: 

1. I can't find the proofview.css string in the heading to make the change.
2. The note that is written upside down in the top left corner does not appear in HTML. 
3. On comment 1, the editor is listed as "kj mb." Can you put two sets of initials within one code or do I need to do something else? 
4. At the bottom of the Document Metadata section at the top of the HTML is a line saying "Description of original facsimile:" but nothing is displayed. What is supposed to go here? Is this supposed to be the upside down note that Lili wrote? 
5. Should I tag "Lillemor og Søn ("your sweet little mother and son")? If so, who are they? 

Thank you!

Kristin

**Comment by ProfPLC** [comment]
@kklimek1 and @bcristiana -- Thank you so much for your patience. @RJP43 has informed me that the Allatini Chapter and Hirschfeld chapter are ready for HTML proofing. Please refer to [the first comment on this issue](https://github.com/RJP43/LiliElbe_EngagedLearners/issues/44#issue-436294562) for instructions on how to proof these files and provide changes needed to be made on your text's respective sheet in the [Archival Materials--HTML Proofing Google Spreadsheet](https://docs.google.com/spreadsheets/d/1d-tIQqdtcEGnDzsQoihkOH9H7JceLshsnrBRkQURU90/edit?usp=sharing). Both chapter HTML files can be found in the [French Archives HTML_ProofingViews folder](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/French_archive/HTML_ProofingViews). If you are confident in your abilities to edit the XML do so and just reflect the changes you make on the above linked Google Spreadsheet. Also, as you complete proofing and wish to see the XML re-transformed into HTML please come back to this issue and call out to @RJP43 or @cmccraw to re-run the HTML transformation. :+1: :smiley:

**Comment by kklimek1** [comment]
Thank you! I'll start working on proofing over this weekend.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kejcat** [comment]
I am not sure what to do about the headers for HTML proofing. I have proofed 19310807LEGarland and 19310724LEGarland. In 19310807LEGarland I noticed that there was no expanded header information, so I reconstructed it. I didn't make any corrections to the header for 19310724LEGarland, though. I just noticed that there is a file in the folder for each letter that is called [file name]_header.xml, though the information about me and Maiken as transcribers/translators is not quite right. I want to make sure that I'm proofing headers correctly going forward. Should there be expanded heading information within in the xml file for the letter, or should I leave header information in the separate header file? If we're using a separate header file, I'll make corrections on the information about me and Maiken. Thank you! Kristin

**Comment by kejcat** [comment]
I have a question about coding closers in letters. Do you need to code for paragraph breaks in order for the text to display correctly in the closing salutation? The closing salutation in 19310616LEGarland has three lines of closing before the signature. It currently is not displaying in HTML, so I'm not sure if it is coded correctly. Thank you. Kristin

**Comment by kejcat** [comment]
For letters, do the headers with information on date, place, day of the week, etc. get coding as a segment? Thank you. Kristin

**Comment by kejcat** [comment]
Here are the issues I've found with 19310616LEGarland:

1. I can't find the proofview.css string in the heading to make the change.
2. Which header should I use? (question asked above; repeated here for completeness).
3. Not displaying in HTML:
       - English translation of letter.
       - Day of the week, place, and date that make up the very first line. 
       - Mein brief (note written in red in upper left corner), which includes translator note. 
       - Closing salutation  (question asked above; repeated here for completeness). 
       - Postscript
4. In header info at top of HTML, "Publication Information" displays as "Publication Information"; and "Description of original facsimile"  displays as "Information about the source". Should they be deleted if they don't contain information, or should information be added? 
5. For the translator notes, the word "Translator" appears in the text of the HTML version. I don't think the notes are coded correctly. Should I change them to what's in the Encoding Guidelines? If so, the Main Brief note is surrounded by codes for placement of note and underlining. Where does the note go? 
6. On the translator notes, the source is listed as "kj mb." Can you put two sets of initials within one code or do I need to do something else? (question also asked above re 19310724LEGarland. 

Thanks for bearing with my many questions. 

Kristin

**Comment by cmccraw** [comment]
Hi @kejcat, thanks for documenting the issues that you've come across so well! It looks like most of the Danish Letters were encoded a while ago, so trust your instinct to make the encoding consistent with our current guidelines! 

@RJP43, if you could confirm which TEI header to use for letters (see Kristin's question(s) about headers above), that would be much appreciated!

Re: your most recent questions:

1. The proofview.css string should be in the HTML file for proofing purposes; double-check that you aren't looking for it in the XML? 
2. @RJP43 confirm header for letters?
3. I managed to get the English translation, closing salutation, and post script to show up. However, I can't figure out how to get any of the header information (day of the week, place, and date, along with "Mein brief" annotation) to show up. @RJP43 
4. According to the spreadsheet, @emilydatskou would like to change "Description of original facsimile" to be "Description of original facsimile: to be added"
5. Yes, please change the translator notes' encoding to be consistent with guidelines. 
6. @RJP43 Are two sets of initials okay? 

(+)

7. @RJP43 the closer for German Letter No. 2 is still not showing up (see https://github.com/RJP43/LiliElbe_EngagedLearners/issues/44#issuecomment-493788239, also noted on spreadsheet). 

8. Re: 19311221_ThomsenSHarthern— I managed to get both texts displaying in English and Danish, but having the same issue with header not showing up. @kejcat can you double-check the translation for this letter? The numbering is obviously off, but I'm not sure how the translation aligns here. Thanks!

@kejcat If you haven't already done so, be sure to add your name to the resp statement for HTML proofing once we hear back about the TEI header situation! :) :)
