### ISSUE TITLE
Sanheden article ready for transformation

### ISSUE THREAD

**Issue by kejcat** [RJP43/LiliElbe_EngagedLearners#45]
The Sanheden article is ready. I missed the class where you talked about proofing HTML. I signed up for a Hypothes.is account, but I'm not sure what I need to do next. From reading the lesson for Feb. 28, it looks like I need an HTML Proofing URL. Do I get that from you or Dr. Caughie? Thanks for your help!

**Comment by RJP43** [comment]
@kejcat Thanks for letting me know your text is ready for transformation. 👍  Thank you so much for your hard work! 💟 Unfortunately, the article HTML proofing view transformation is just not ready yet (though having your file as an example will help when I get the chance to finish it).  I won't be able to get it done until the weekend after finals week. 😞 I'm not sure if Emily has next tasks planned for you, but if not I have posted instructions (just today) on how we are moving forward with HTML proofing of the students' Danish letters over on issue #44 and there will likely be texts that could use a second set of eyes especially of someone with your language skills. There are also several documents including the Politiken articles that need encoding and XML proofing ... so pending on what you are up to taking on next there are plenty of options.  However, I imagine we will want to check with Emily before assigning you anything in particular.

**Comment by RJP43** [comment]
I have just now closed your other Sanheden Issue (#41) since we have this new one where we can discuss next steps moving forward with this text. I think I have gone through that other issue resolving all of your expressed concerns. Please, if there is anything else from that issue still unresolved create a list HERE on this issue and I will ping you as I am able to resolve them. Thanks! 👍

**Comment by kejcat** [comment]
Thank you, too, for the immense amount of work you have put in. What did you decide to do on the second set of comments in the translation, the ones that kept getting errors? I want to make sure that I have the coding correct on the copy I have. Kristin

**Comment by RJP43** [comment]
@kejcat I have updated the markup for encoding translator and editor comments in our encoding guidelines. Please let me know if what I have there needs further clarification or if you have any suggestions on how to make our conversation regarding comments more concise and properly represented in the guidelines. Thanks!
